import APPT.Finite9Sparse.Det03Pair4
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
open scoped BigOperators
namespace APPT.Finite9
open SparsePolynomial

def det03Term4Row04 : CoefficientMerge.Poly := [(nat_lit 31, Int.ofNat (nat_lit 2)), (nat_lit 40, Int.ofNat (nat_lit 2)), (nat_lit 41, Int.ofNat (nat_lit 2)), (nat_lit 42, Int.ofNat (nat_lit 2)), (nat_lit 43, Int.ofNat (nat_lit 2)), (nat_lit 44, Int.ofNat (nat_lit 2)), (nat_lit 112, Int.ofNat (nat_lit 2)), (nat_lit 121, Int.ofNat (nat_lit 2)), (nat_lit 122, Int.ofNat (nat_lit 2)), (nat_lit 123, Int.ofNat (nat_lit 2)), (nat_lit 124, Int.ofNat (nat_lit 2)), (nat_lit 125, Int.ofNat (nat_lit 2)), (nat_lit 193, Int.ofNat (nat_lit 2)), (nat_lit 202, Int.ofNat (nat_lit 2)), (nat_lit 203, Int.ofNat (nat_lit 2)), (nat_lit 204, Int.ofNat (nat_lit 2)), (nat_lit 205, Int.ofNat (nat_lit 2)), (nat_lit 206, Int.ofNat (nat_lit 2)), (nat_lit 274, Int.ofNat (nat_lit 2)), (nat_lit 283, Int.ofNat (nat_lit 4)), (nat_lit 284, Int.ofNat (nat_lit 4)), (nat_lit 285, Int.ofNat (nat_lit 4)), (nat_lit 286, Int.ofNat (nat_lit 2)), (nat_lit 287, Int.ofNat (nat_lit 2)), (nat_lit 364, Int.ofNat (nat_lit 2)), (nat_lit 365, Int.ofNat (nat_lit 4)), (nat_lit 366, Int.ofNat (nat_lit 4)), (nat_lit 367, Int.ofNat (nat_lit 2)), (nat_lit 368, Int.ofNat (nat_lit 2)), (nat_lit 374, Int.ofNat (nat_lit 2)), (nat_lit 375, Int.ofNat (nat_lit 4)), (nat_lit 376, Int.ofNat (nat_lit 2)), (nat_lit 377, Int.ofNat (nat_lit 2)), (nat_lit 384, Int.ofNat (nat_lit 2)), (nat_lit 385, Int.ofNat (nat_lit 2)), (nat_lit 386, Int.ofNat (nat_lit 2))]
theorem det03Term4Row04_decode : SparsePolynomial.decodeCubic 9 det03Term4Row04 = SparsePolynomial.monoTimes [4] (-1 : Int) det03Pair4 := by decide +kernel
theorem eval_det03Term4Row04 (g : Fin 9 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 9) det03Term4Row04 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [4]*SparsePolynomial.eval (gapValues g) det03Pair4 := by
  rw [← SparsePolynomial.eval_decodeCubic, det03Term4Row04_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det03Term4Row05 : CoefficientMerge.Poly := [(nat_lit 32, Int.ofNat (nat_lit 2)), (nat_lit 41, Int.ofNat (nat_lit 2)), (nat_lit 50, Int.ofNat (nat_lit 2)), (nat_lit 51, Int.ofNat (nat_lit 2)), (nat_lit 52, Int.ofNat (nat_lit 2)), (nat_lit 53, Int.ofNat (nat_lit 2)), (nat_lit 113, Int.ofNat (nat_lit 2)), (nat_lit 122, Int.ofNat (nat_lit 2)), (nat_lit 131, Int.ofNat (nat_lit 2)), (nat_lit 132, Int.ofNat (nat_lit 2)), (nat_lit 133, Int.ofNat (nat_lit 2)), (nat_lit 134, Int.ofNat (nat_lit 2)), (nat_lit 194, Int.ofNat (nat_lit 2)), (nat_lit 203, Int.ofNat (nat_lit 2)), (nat_lit 212, Int.ofNat (nat_lit 2)), (nat_lit 213, Int.ofNat (nat_lit 2)), (nat_lit 214, Int.ofNat (nat_lit 2)), (nat_lit 215, Int.ofNat (nat_lit 2)), (nat_lit 275, Int.ofNat (nat_lit 2)), (nat_lit 284, Int.ofNat (nat_lit 4)), (nat_lit 293, Int.ofNat (nat_lit 4)), (nat_lit 294, Int.ofNat (nat_lit 4)), (nat_lit 295, Int.ofNat (nat_lit 2)), (nat_lit 296, Int.ofNat (nat_lit 2)), (nat_lit 365, Int.ofNat (nat_lit 2)), (nat_lit 374, Int.ofNat (nat_lit 4)), (nat_lit 375, Int.ofNat (nat_lit 4)), (nat_lit 376, Int.ofNat (nat_lit 2)), (nat_lit 377, Int.ofNat (nat_lit 2)), (nat_lit 455, Int.ofNat (nat_lit 2)), (nat_lit 456, Int.ofNat (nat_lit 4)), (nat_lit 457, Int.ofNat (nat_lit 2)), (nat_lit 458, Int.ofNat (nat_lit 2)), (nat_lit 465, Int.ofNat (nat_lit 2)), (nat_lit 466, Int.ofNat (nat_lit 2)), (nat_lit 467, Int.ofNat (nat_lit 2))]
theorem det03Term4Row05_decode : SparsePolynomial.decodeCubic 9 det03Term4Row05 = SparsePolynomial.monoTimes [5] (-1 : Int) det03Pair4 := by decide +kernel
theorem eval_det03Term4Row05 (g : Fin 9 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 9) det03Term4Row05 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [5]*SparsePolynomial.eval (gapValues g) det03Pair4 := by
  rw [← SparsePolynomial.eval_decodeCubic, det03Term4Row05_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det03Term4Row06 : CoefficientMerge.Poly := [(nat_lit 33, Int.ofNat (nat_lit 2)), (nat_lit 42, Int.ofNat (nat_lit 2)), (nat_lit 51, Int.ofNat (nat_lit 2)), (nat_lit 60, Int.ofNat (nat_lit 2)), (nat_lit 61, Int.ofNat (nat_lit 2)), (nat_lit 62, Int.ofNat (nat_lit 2)), (nat_lit 114, Int.ofNat (nat_lit 2)), (nat_lit 123, Int.ofNat (nat_lit 2)), (nat_lit 132, Int.ofNat (nat_lit 2)), (nat_lit 141, Int.ofNat (nat_lit 2)), (nat_lit 142, Int.ofNat (nat_lit 2)), (nat_lit 143, Int.ofNat (nat_lit 2)), (nat_lit 195, Int.ofNat (nat_lit 2)), (nat_lit 204, Int.ofNat (nat_lit 2)), (nat_lit 213, Int.ofNat (nat_lit 2)), (nat_lit 222, Int.ofNat (nat_lit 2)), (nat_lit 223, Int.ofNat (nat_lit 2)), (nat_lit 224, Int.ofNat (nat_lit 2)), (nat_lit 276, Int.ofNat (nat_lit 2)), (nat_lit 285, Int.ofNat (nat_lit 4)), (nat_lit 294, Int.ofNat (nat_lit 4)), (nat_lit 303, Int.ofNat (nat_lit 4)), (nat_lit 304, Int.ofNat (nat_lit 2)), (nat_lit 305, Int.ofNat (nat_lit 2)), (nat_lit 366, Int.ofNat (nat_lit 2)), (nat_lit 375, Int.ofNat (nat_lit 4)), (nat_lit 384, Int.ofNat (nat_lit 4)), (nat_lit 385, Int.ofNat (nat_lit 2)), (nat_lit 386, Int.ofNat (nat_lit 2)), (nat_lit 456, Int.ofNat (nat_lit 2)), (nat_lit 465, Int.ofNat (nat_lit 4)), (nat_lit 466, Int.ofNat (nat_lit 2)), (nat_lit 467, Int.ofNat (nat_lit 2)), (nat_lit 546, Int.ofNat (nat_lit 2)), (nat_lit 547, Int.ofNat (nat_lit 2)), (nat_lit 548, Int.ofNat (nat_lit 2))]
theorem det03Term4Row06_decode : SparsePolynomial.decodeCubic 9 det03Term4Row06 = SparsePolynomial.monoTimes [6] (-1 : Int) det03Pair4 := by decide +kernel
theorem eval_det03Term4Row06 (g : Fin 9 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 9) det03Term4Row06 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [6]*SparsePolynomial.eval (gapValues g) det03Pair4 := by
  rw [← SparsePolynomial.eval_decodeCubic, det03Term4Row06_decode, SparsePolynomial.eval_monoTimes]
  norm_num

end APPT.Finite9
