-- FLAT_COEFFICIENT_MERGES_V1: kernel-checked literal barriers.
import APPT.Finite9Sparse.Data
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
open scoped BigOperators
namespace APPT.Finite9
open SparsePolynomial

def square0 : SparsePolynomial.Poly := [([nat_lit 0, nat_lit 0], Int.ofNat (nat_lit 1)), ([nat_lit 0, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 2], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 1], Int.ofNat (nat_lit 1)), ([nat_lit 1, nat_lit 2], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 2], Int.ofNat (nat_lit 1)), ([nat_lit 2, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 1)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 1)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 1)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 1)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 1)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 1))]
theorem square0_data : square0 = SparsePolynomial.trim (SparsePolynomial.mul polyY0 polyY0) := by decide +kernel
theorem eval_square0 (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) square0 = (spectrum g 0)^2 := by
  rw [square0_data, SparsePolynomial.eval_trim, SparsePolynomial.eval_mul, eval_polyY0]
  ring
def square1 : SparsePolynomial.Poly := [([nat_lit 1, nat_lit 1], Int.ofNat (nat_lit 1)), ([nat_lit 1, nat_lit 2], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 2], Int.ofNat (nat_lit 1)), ([nat_lit 2, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 1)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 1)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 1)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 1)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 1)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 1))]
theorem square1_data : square1 = SparsePolynomial.trim (SparsePolynomial.mul polyY1 polyY1) := by decide +kernel
theorem eval_square1 (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) square1 = (spectrum g 1)^2 := by
  rw [square1_data, SparsePolynomial.eval_trim, SparsePolynomial.eval_mul, eval_polyY1]
  ring
def square2 : SparsePolynomial.Poly := [([nat_lit 2, nat_lit 2], Int.ofNat (nat_lit 1)), ([nat_lit 2, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 1)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 1)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 1)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 1)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 1)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 1))]
theorem square2_data : square2 = SparsePolynomial.trim (SparsePolynomial.mul polyY2 polyY2) := by decide +kernel
theorem eval_square2 (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) square2 = (spectrum g 2)^2 := by
  rw [square2_data, SparsePolynomial.eval_trim, SparsePolynomial.eval_mul, eval_polyY2]
  ring
def square3 : SparsePolynomial.Poly := [([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 1)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 1)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 1)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 1)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 1)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 1))]
theorem square3_data : square3 = SparsePolynomial.trim (SparsePolynomial.mul polyY3 polyY3) := by decide +kernel
theorem eval_square3 (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) square3 = (spectrum g 3)^2 := by
  rw [square3_data, SparsePolynomial.eval_trim, SparsePolynomial.eval_mul, eval_polyY3]
  ring
def square4 : SparsePolynomial.Poly := [([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 1)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 1)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 1)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 1)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 1))]
theorem square4_data : square4 = SparsePolynomial.trim (SparsePolynomial.mul polyY4 polyY4) := by decide +kernel
theorem eval_square4 (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) square4 = (spectrum g 4)^2 := by
  rw [square4_data, SparsePolynomial.eval_trim, SparsePolynomial.eval_mul, eval_polyY4]
  ring
def square5 : SparsePolynomial.Poly := [([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 1)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 1)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 1)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 1))]
theorem square5_data : square5 = SparsePolynomial.trim (SparsePolynomial.mul polyY5 polyY5) := by decide +kernel
theorem eval_square5 (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) square5 = (spectrum g 5)^2 := by
  rw [square5_data, SparsePolynomial.eval_trim, SparsePolynomial.eval_mul, eval_polyY5]
  ring
def square6 : SparsePolynomial.Poly := [([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 1)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 1)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 1))]
theorem square6_data : square6 = SparsePolynomial.trim (SparsePolynomial.mul polyY6 polyY6) := by decide +kernel
theorem eval_square6 (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) square6 = (spectrum g 6)^2 := by
  rw [square6_data, SparsePolynomial.eval_trim, SparsePolynomial.eval_mul, eval_polyY6]
  ring
def square7 : SparsePolynomial.Poly := [([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 1)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 1))]
theorem square7_data : square7 = SparsePolynomial.trim (SparsePolynomial.mul polyY7 polyY7) := by decide +kernel
theorem eval_square7 (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) square7 = (spectrum g 7)^2 := by
  rw [square7_data, SparsePolynomial.eval_trim, SparsePolynomial.eval_mul, eval_polyY7]
  ring
def square8 : SparsePolynomial.Poly := [([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 1))]
theorem square8_data : square8 = SparsePolynomial.trim (SparsePolynomial.mul polyY8 polyY8) := by decide +kernel
theorem eval_square8 (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) square8 = (spectrum g 8)^2 := by
  rw [square8_data, SparsePolynomial.eval_trim, SparsePolynomial.eval_mul, eval_polyY8]
  ring
def polySquares : SparsePolynomial.Poly := [([nat_lit 0, nat_lit 0], Int.ofNat (nat_lit 1)), ([nat_lit 0, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 2], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 2], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 4], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 2], Int.ofNat (nat_lit 3)), ([nat_lit 2, nat_lit 3], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 4], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 5], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 6], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 7], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 8], Int.ofNat (nat_lit 6)), ([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 8)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 5)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 10)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 10)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 10)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 10)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 6)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 12)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 12)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 12)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 7)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 14)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 14)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 16)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 9))]
def polySquares_data_flat000 : SparsePolynomial.Poly := [([nat_lit 0, nat_lit 0], Int.ofNat (nat_lit 1)), ([nat_lit 0, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 2], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 2], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 4], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 2], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 4], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 2))]
theorem polySquares_data_flat000_step : polySquares_data_flat000 = (SparsePolynomial.merge square0 square1) := by decide +kernel
theorem polySquares_data_flat000_original : polySquares_data_flat000 = (SparsePolynomial.merge square0 square1) := by
  rw [polySquares_data_flat000_step]
def polySquares_data_flat001 : SparsePolynomial.Poly := [([nat_lit 2, nat_lit 2], Int.ofNat (nat_lit 1)), ([nat_lit 2, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 2, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 2))]
theorem polySquares_data_flat001_step : polySquares_data_flat001 = (SparsePolynomial.merge square2 square3) := by decide +kernel
theorem polySquares_data_flat001_original : polySquares_data_flat001 = (SparsePolynomial.merge square2 square3) := by
  rw [polySquares_data_flat001_step]
def polySquares_data_flat002 : SparsePolynomial.Poly := [([nat_lit 0, nat_lit 0], Int.ofNat (nat_lit 1)), ([nat_lit 0, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 2], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 2], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 4], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 2], Int.ofNat (nat_lit 3)), ([nat_lit 2, nat_lit 3], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 4], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 5], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 6], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 7], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 8], Int.ofNat (nat_lit 6)), ([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 8)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 4)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 8)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 8)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 8)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 8)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 8)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 8)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 8)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 4))]
theorem polySquares_data_flat002_step : polySquares_data_flat002 = (SparsePolynomial.merge polySquares_data_flat000 polySquares_data_flat001) := by decide +kernel
theorem polySquares_data_flat002_original : polySquares_data_flat002 = (SparsePolynomial.merge (SparsePolynomial.merge square0 square1) (SparsePolynomial.merge square2 square3)) := by
  rw [polySquares_data_flat002_step, polySquares_data_flat000_original, polySquares_data_flat001_original]
def polySquares_data_flat003 : SparsePolynomial.Poly := [([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 1)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 2))]
theorem polySquares_data_flat003_step : polySquares_data_flat003 = (SparsePolynomial.merge square4 square5) := by decide +kernel
theorem polySquares_data_flat003_original : polySquares_data_flat003 = (SparsePolynomial.merge square4 square5) := by
  rw [polySquares_data_flat003_step]
def polySquares_data_flat004 : SparsePolynomial.Poly := [([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 1)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 2))]
theorem polySquares_data_flat004_step : polySquares_data_flat004 = (SparsePolynomial.merge square7 square8) := by decide +kernel
theorem polySquares_data_flat004_original : polySquares_data_flat004 = (SparsePolynomial.merge square7 square8) := by
  rw [polySquares_data_flat004_step]
def polySquares_data_flat005 : SparsePolynomial.Poly := [([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 1)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 3))]
theorem polySquares_data_flat005_step : polySquares_data_flat005 = (SparsePolynomial.merge square6 polySquares_data_flat004) := by decide +kernel
theorem polySquares_data_flat005_original : polySquares_data_flat005 = (SparsePolynomial.merge square6 (SparsePolynomial.merge square7 square8)) := by
  rw [polySquares_data_flat005_step, polySquares_data_flat004_original]
def polySquares_data_flat006 : SparsePolynomial.Poly := [([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 1)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 3)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 6)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 6)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 8)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 5))]
theorem polySquares_data_flat006_step : polySquares_data_flat006 = (SparsePolynomial.merge polySquares_data_flat003 polySquares_data_flat005) := by decide +kernel
theorem polySquares_data_flat006_original : polySquares_data_flat006 = (SparsePolynomial.merge (SparsePolynomial.merge square4 square5) (SparsePolynomial.merge square6 (SparsePolynomial.merge square7 square8))) := by
  rw [polySquares_data_flat006_step, polySquares_data_flat003_original, polySquares_data_flat005_original]
def polySquares_data_flat007 : SparsePolynomial.Poly := [([nat_lit 0, nat_lit 0], Int.ofNat (nat_lit 1)), ([nat_lit 0, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 2], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 2], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 4], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 2], Int.ofNat (nat_lit 3)), ([nat_lit 2, nat_lit 3], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 4], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 5], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 6], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 7], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 8], Int.ofNat (nat_lit 6)), ([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 8)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 5)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 10)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 10)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 10)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 10)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 6)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 12)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 12)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 12)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 7)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 14)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 14)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 16)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 9))]
theorem polySquares_data_flat007_step : polySquares_data_flat007 = (SparsePolynomial.merge polySquares_data_flat002 polySquares_data_flat006) := by decide +kernel
theorem polySquares_data_flat007_original : polySquares_data_flat007 = (SparsePolynomial.merge (SparsePolynomial.merge (SparsePolynomial.merge square0 square1) (SparsePolynomial.merge square2 square3)) (SparsePolynomial.merge (SparsePolynomial.merge square4 square5) (SparsePolynomial.merge square6 (SparsePolynomial.merge square7 square8)))) := by
  rw [polySquares_data_flat007_step, polySquares_data_flat002_original, polySquares_data_flat006_original]
def polySquares_data_flat008 : SparsePolynomial.Poly := [([nat_lit 0, nat_lit 0], Int.ofNat (nat_lit 1)), ([nat_lit 0, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 2], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 3], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 4], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 5], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 6], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 7], Int.ofNat (nat_lit 2)), ([nat_lit 0, nat_lit 8], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 1], Int.ofNat (nat_lit 2)), ([nat_lit 1, nat_lit 2], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 4], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 5], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 6], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 7], Int.ofNat (nat_lit 4)), ([nat_lit 1, nat_lit 8], Int.ofNat (nat_lit 4)), ([nat_lit 2, nat_lit 2], Int.ofNat (nat_lit 3)), ([nat_lit 2, nat_lit 3], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 4], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 5], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 6], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 7], Int.ofNat (nat_lit 6)), ([nat_lit 2, nat_lit 8], Int.ofNat (nat_lit 6)), ([nat_lit 3, nat_lit 3], Int.ofNat (nat_lit 4)), ([nat_lit 3, nat_lit 4], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 5], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 6], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 3, nat_lit 8], Int.ofNat (nat_lit 8)), ([nat_lit 4, nat_lit 4], Int.ofNat (nat_lit 5)), ([nat_lit 4, nat_lit 5], Int.ofNat (nat_lit 10)), ([nat_lit 4, nat_lit 6], Int.ofNat (nat_lit 10)), ([nat_lit 4, nat_lit 7], Int.ofNat (nat_lit 10)), ([nat_lit 4, nat_lit 8], Int.ofNat (nat_lit 10)), ([nat_lit 5, nat_lit 5], Int.ofNat (nat_lit 6)), ([nat_lit 5, nat_lit 6], Int.ofNat (nat_lit 12)), ([nat_lit 5, nat_lit 7], Int.ofNat (nat_lit 12)), ([nat_lit 5, nat_lit 8], Int.ofNat (nat_lit 12)), ([nat_lit 6, nat_lit 6], Int.ofNat (nat_lit 7)), ([nat_lit 6, nat_lit 7], Int.ofNat (nat_lit 14)), ([nat_lit 6, nat_lit 8], Int.ofNat (nat_lit 14)), ([nat_lit 7, nat_lit 7], Int.ofNat (nat_lit 8)), ([nat_lit 7, nat_lit 8], Int.ofNat (nat_lit 16)), ([nat_lit 8, nat_lit 8], Int.ofNat (nat_lit 9))]
theorem polySquares_data_flat008_step : polySquares_data_flat008 = (SparsePolynomial.trim polySquares_data_flat007) := by decide +kernel
theorem polySquares_data_flat008_original : polySquares_data_flat008 = (SparsePolynomial.trim (SparsePolynomial.merge (SparsePolynomial.merge (SparsePolynomial.merge square0 square1) (SparsePolynomial.merge square2 square3)) (SparsePolynomial.merge (SparsePolynomial.merge square4 square5) (SparsePolynomial.merge square6 (SparsePolynomial.merge square7 square8))))) := by
  rw [polySquares_data_flat008_step, polySquares_data_flat007_original]
theorem polySquares_data : polySquares = SparsePolynomial.trim (SparsePolynomial.merge (SparsePolynomial.merge (SparsePolynomial.merge square0 square1) (SparsePolynomial.merge square2 square3)) (SparsePolynomial.merge (SparsePolynomial.merge square4 square5) (SparsePolynomial.merge square6 (SparsePolynomial.merge square7 square8)))) := by
  have h : polySquares = polySquares_data_flat008 := by decide +kernel
  exact h.trans polySquares_data_flat008_original
theorem eval_polySquares (g : Fin 9 → ℝ) : SparsePolynomial.eval (gapValues g) polySquares = squareTotal g := by
  rw [polySquares_data, SparsePolynomial.eval_trim]
  simp only [SparsePolynomial.eval_merge, eval_square0, eval_square1, eval_square2, eval_square3, eval_square4, eval_square5, eval_square6, eval_square7, eval_square8]
  simp [squareTotal, Fin.sum_univ_succ]
  <;> ring

end APPT.Finite9
