import ExplicitBundle
#print axioms BapatExplicit.inversionCount_eq
#print axioms BapatExplicit.qPermanent_eq
#print axioms BapatExplicit.endpointDerivative_eq
#print axioms BapatExplicit.twoColumnGram_mul
#print axioms BapatExplicit.perturb_eq
#print axioms BapatExplicit.cast_triple_pow
#print axioms BapatExplicit.gamma_cast
#print axioms BapatExplicit.secondBound_cast
#print axioms BapatExplicit.epsilon_cast
#print axioms BapatExplicit.intervalLength_cast
#print axioms BapatExplicit.q0_cast
#print axioms BapatExplicit.q0_complex_cast
#print axioms BapatExplicit.epsilon_positive
#print axioms BapatExplicit.intervalLength_positive
#print axioms BapatExplicit.toComplex_norm_sq
#print axioms BapatExplicit.integer_coordinate_norm_bounds
#print axioms BapatExplicit.vector_norm_sq_bounds
#print axioms BapatExplicit.matrix_entry_norm_bound
#print axioms BapatExplicit.toComplex_re
#print axioms BapatExplicit.toComplex_im
#print axioms BapatExplicit.matrix_rational_entries
#print axioms BapatExplicit.explicitMatrix_rational_entries
#print axioms BapatExplicit.integer_norm_gap_at_least_one
#print axioms BapatExplicit.permanentNorm_eq_fischer
#print axioms BapatExplicit.wedgeNorm_eq_fischer
#print axioms BapatExplicit.matrix_endpoint_unit_gap
#print axioms BapatExplicit.explicit_rational_counterexample
#print axioms BapatExplicit.explicit_not_monotone
#print axioms BapatExplicit.original_conjecture_false_from_explicit
#print axioms BapatExplicit.explicit_qPermanent_real
