import APPT.Finite15Sparse.Det04Pair1
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
open scoped BigOperators
namespace APPT.Finite15
open SparsePolynomial

def det04Term1Row00 : CoefficientMerge.Poly := [(nat_lit 17, Int.negSucc (nat_lit 0)), (nat_lit 18, Int.negSucc (nat_lit 0)), (nat_lit 19, Int.negSucc (nat_lit 0)), (nat_lit 20, Int.negSucc (nat_lit 0)), (nat_lit 21, Int.negSucc (nat_lit 0)), (nat_lit 22, Int.negSucc (nat_lit 0)), (nat_lit 23, Int.negSucc (nat_lit 0)), (nat_lit 24, Int.negSucc (nat_lit 0)), (nat_lit 32, Int.negSucc (nat_lit 0)), (nat_lit 33, Int.negSucc (nat_lit 1)), (nat_lit 34, Int.negSucc (nat_lit 1)), (nat_lit 35, Int.negSucc (nat_lit 1)), (nat_lit 36, Int.negSucc (nat_lit 1)), (nat_lit 37, Int.negSucc (nat_lit 1)), (nat_lit 38, Int.negSucc (nat_lit 1)), (nat_lit 39, Int.negSucc (nat_lit 1)), (nat_lit 40, Int.negSucc (nat_lit 0)), (nat_lit 41, Int.negSucc (nat_lit 0)), (nat_lit 48, Int.negSucc (nat_lit 0)), (nat_lit 49, Int.negSucc (nat_lit 1)), (nat_lit 50, Int.negSucc (nat_lit 1)), (nat_lit 51, Int.negSucc (nat_lit 1)), (nat_lit 52, Int.negSucc (nat_lit 1)), (nat_lit 53, Int.negSucc (nat_lit 1)), (nat_lit 54, Int.negSucc (nat_lit 1)), (nat_lit 55, Int.negSucc (nat_lit 0)), (nat_lit 56, Int.negSucc (nat_lit 0)), (nat_lit 64, Int.negSucc (nat_lit 0)), (nat_lit 65, Int.negSucc (nat_lit 1)), (nat_lit 66, Int.negSucc (nat_lit 1)), (nat_lit 67, Int.negSucc (nat_lit 1)), (nat_lit 68, Int.negSucc (nat_lit 1)), (nat_lit 69, Int.negSucc (nat_lit 1)), (nat_lit 70, Int.negSucc (nat_lit 0)), (nat_lit 71, Int.negSucc (nat_lit 0)), (nat_lit 80, Int.negSucc (nat_lit 0)), (nat_lit 81, Int.negSucc (nat_lit 1)), (nat_lit 82, Int.negSucc (nat_lit 1)), (nat_lit 83, Int.negSucc (nat_lit 1)), (nat_lit 84, Int.negSucc (nat_lit 1)), (nat_lit 85, Int.negSucc (nat_lit 0)), (nat_lit 86, Int.negSucc (nat_lit 0)), (nat_lit 96, Int.negSucc (nat_lit 0)), (nat_lit 97, Int.negSucc (nat_lit 1)), (nat_lit 98, Int.negSucc (nat_lit 1)), (nat_lit 99, Int.negSucc (nat_lit 1)), (nat_lit 100, Int.negSucc (nat_lit 0)), (nat_lit 101, Int.negSucc (nat_lit 0)), (nat_lit 112, Int.negSucc (nat_lit 0)), (nat_lit 113, Int.negSucc (nat_lit 1)), (nat_lit 114, Int.negSucc (nat_lit 1)), (nat_lit 115, Int.negSucc (nat_lit 0)), (nat_lit 116, Int.negSucc (nat_lit 0)), (nat_lit 128, Int.negSucc (nat_lit 0)), (nat_lit 129, Int.negSucc (nat_lit 1)), (nat_lit 130, Int.negSucc (nat_lit 0)), (nat_lit 131, Int.negSucc (nat_lit 0)), (nat_lit 144, Int.negSucc (nat_lit 0)), (nat_lit 145, Int.negSucc (nat_lit 0)), (nat_lit 146, Int.negSucc (nat_lit 0))]
theorem det04Term1Row00_decode : SparsePolynomial.decodeCubic 15 det04Term1Row00 = SparsePolynomial.monoTimes [0] (-1 : Int) det04Pair1 := by decide +kernel
theorem eval_det04Term1Row00 (g : Fin 15 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 15) det04Term1Row00 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [0]*SparsePolynomial.eval (gapValues g) det04Pair1 := by
  rw [← SparsePolynomial.eval_decodeCubic, det04Term1Row00_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det04Term1Row01 : CoefficientMerge.Poly := [(nat_lit 242, Int.negSucc (nat_lit 0)), (nat_lit 243, Int.negSucc (nat_lit 0)), (nat_lit 244, Int.negSucc (nat_lit 0)), (nat_lit 245, Int.negSucc (nat_lit 0)), (nat_lit 246, Int.negSucc (nat_lit 0)), (nat_lit 247, Int.negSucc (nat_lit 0)), (nat_lit 248, Int.negSucc (nat_lit 0)), (nat_lit 249, Int.negSucc (nat_lit 0)), (nat_lit 257, Int.negSucc (nat_lit 0)), (nat_lit 258, Int.negSucc (nat_lit 1)), (nat_lit 259, Int.negSucc (nat_lit 1)), (nat_lit 260, Int.negSucc (nat_lit 1)), (nat_lit 261, Int.negSucc (nat_lit 1)), (nat_lit 262, Int.negSucc (nat_lit 1)), (nat_lit 263, Int.negSucc (nat_lit 1)), (nat_lit 264, Int.negSucc (nat_lit 1)), (nat_lit 265, Int.negSucc (nat_lit 0)), (nat_lit 266, Int.negSucc (nat_lit 0)), (nat_lit 273, Int.negSucc (nat_lit 0)), (nat_lit 274, Int.negSucc (nat_lit 1)), (nat_lit 275, Int.negSucc (nat_lit 1)), (nat_lit 276, Int.negSucc (nat_lit 1)), (nat_lit 277, Int.negSucc (nat_lit 1)), (nat_lit 278, Int.negSucc (nat_lit 1)), (nat_lit 279, Int.negSucc (nat_lit 1)), (nat_lit 280, Int.negSucc (nat_lit 0)), (nat_lit 281, Int.negSucc (nat_lit 0)), (nat_lit 289, Int.negSucc (nat_lit 0)), (nat_lit 290, Int.negSucc (nat_lit 1)), (nat_lit 291, Int.negSucc (nat_lit 1)), (nat_lit 292, Int.negSucc (nat_lit 1)), (nat_lit 293, Int.negSucc (nat_lit 1)), (nat_lit 294, Int.negSucc (nat_lit 1)), (nat_lit 295, Int.negSucc (nat_lit 0)), (nat_lit 296, Int.negSucc (nat_lit 0)), (nat_lit 305, Int.negSucc (nat_lit 0)), (nat_lit 306, Int.negSucc (nat_lit 1)), (nat_lit 307, Int.negSucc (nat_lit 1)), (nat_lit 308, Int.negSucc (nat_lit 1)), (nat_lit 309, Int.negSucc (nat_lit 1)), (nat_lit 310, Int.negSucc (nat_lit 0)), (nat_lit 311, Int.negSucc (nat_lit 0)), (nat_lit 321, Int.negSucc (nat_lit 0)), (nat_lit 322, Int.negSucc (nat_lit 1)), (nat_lit 323, Int.negSucc (nat_lit 1)), (nat_lit 324, Int.negSucc (nat_lit 1)), (nat_lit 325, Int.negSucc (nat_lit 0)), (nat_lit 326, Int.negSucc (nat_lit 0)), (nat_lit 337, Int.negSucc (nat_lit 0)), (nat_lit 338, Int.negSucc (nat_lit 1)), (nat_lit 339, Int.negSucc (nat_lit 1)), (nat_lit 340, Int.negSucc (nat_lit 0)), (nat_lit 341, Int.negSucc (nat_lit 0)), (nat_lit 353, Int.negSucc (nat_lit 0)), (nat_lit 354, Int.negSucc (nat_lit 1)), (nat_lit 355, Int.negSucc (nat_lit 0)), (nat_lit 356, Int.negSucc (nat_lit 0)), (nat_lit 369, Int.negSucc (nat_lit 0)), (nat_lit 370, Int.negSucc (nat_lit 0)), (nat_lit 371, Int.negSucc (nat_lit 0))]
theorem det04Term1Row01_decode : SparsePolynomial.decodeCubic 15 det04Term1Row01 = SparsePolynomial.monoTimes [1] (-1 : Int) det04Pair1 := by decide +kernel
theorem eval_det04Term1Row01 (g : Fin 15 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 15) det04Term1Row01 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [1]*SparsePolynomial.eval (gapValues g) det04Pair1 := by
  rw [← SparsePolynomial.eval_decodeCubic, det04Term1Row01_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det04Term1Row02 : CoefficientMerge.Poly := [(nat_lit 257, Int.negSucc (nat_lit 0)), (nat_lit 258, Int.negSucc (nat_lit 0)), (nat_lit 259, Int.negSucc (nat_lit 0)), (nat_lit 260, Int.negSucc (nat_lit 0)), (nat_lit 261, Int.negSucc (nat_lit 0)), (nat_lit 262, Int.negSucc (nat_lit 0)), (nat_lit 263, Int.negSucc (nat_lit 0)), (nat_lit 264, Int.negSucc (nat_lit 0)), (nat_lit 482, Int.negSucc (nat_lit 0)), (nat_lit 483, Int.negSucc (nat_lit 1)), (nat_lit 484, Int.negSucc (nat_lit 1)), (nat_lit 485, Int.negSucc (nat_lit 1)), (nat_lit 486, Int.negSucc (nat_lit 1)), (nat_lit 487, Int.negSucc (nat_lit 1)), (nat_lit 488, Int.negSucc (nat_lit 1)), (nat_lit 489, Int.negSucc (nat_lit 1)), (nat_lit 490, Int.negSucc (nat_lit 0)), (nat_lit 491, Int.negSucc (nat_lit 0)), (nat_lit 498, Int.negSucc (nat_lit 0)), (nat_lit 499, Int.negSucc (nat_lit 1)), (nat_lit 500, Int.negSucc (nat_lit 1)), (nat_lit 501, Int.negSucc (nat_lit 1)), (nat_lit 502, Int.negSucc (nat_lit 1)), (nat_lit 503, Int.negSucc (nat_lit 1)), (nat_lit 504, Int.negSucc (nat_lit 1)), (nat_lit 505, Int.negSucc (nat_lit 0)), (nat_lit 506, Int.negSucc (nat_lit 0)), (nat_lit 514, Int.negSucc (nat_lit 0)), (nat_lit 515, Int.negSucc (nat_lit 1)), (nat_lit 516, Int.negSucc (nat_lit 1)), (nat_lit 517, Int.negSucc (nat_lit 1)), (nat_lit 518, Int.negSucc (nat_lit 1)), (nat_lit 519, Int.negSucc (nat_lit 1)), (nat_lit 520, Int.negSucc (nat_lit 0)), (nat_lit 521, Int.negSucc (nat_lit 0)), (nat_lit 530, Int.negSucc (nat_lit 0)), (nat_lit 531, Int.negSucc (nat_lit 1)), (nat_lit 532, Int.negSucc (nat_lit 1)), (nat_lit 533, Int.negSucc (nat_lit 1)), (nat_lit 534, Int.negSucc (nat_lit 1)), (nat_lit 535, Int.negSucc (nat_lit 0)), (nat_lit 536, Int.negSucc (nat_lit 0)), (nat_lit 546, Int.negSucc (nat_lit 0)), (nat_lit 547, Int.negSucc (nat_lit 1)), (nat_lit 548, Int.negSucc (nat_lit 1)), (nat_lit 549, Int.negSucc (nat_lit 1)), (nat_lit 550, Int.negSucc (nat_lit 0)), (nat_lit 551, Int.negSucc (nat_lit 0)), (nat_lit 562, Int.negSucc (nat_lit 0)), (nat_lit 563, Int.negSucc (nat_lit 1)), (nat_lit 564, Int.negSucc (nat_lit 1)), (nat_lit 565, Int.negSucc (nat_lit 0)), (nat_lit 566, Int.negSucc (nat_lit 0)), (nat_lit 578, Int.negSucc (nat_lit 0)), (nat_lit 579, Int.negSucc (nat_lit 1)), (nat_lit 580, Int.negSucc (nat_lit 0)), (nat_lit 581, Int.negSucc (nat_lit 0)), (nat_lit 594, Int.negSucc (nat_lit 0)), (nat_lit 595, Int.negSucc (nat_lit 0)), (nat_lit 596, Int.negSucc (nat_lit 0))]
theorem det04Term1Row02_decode : SparsePolynomial.decodeCubic 15 det04Term1Row02 = SparsePolynomial.monoTimes [2] (-1 : Int) det04Pair1 := by decide +kernel
theorem eval_det04Term1Row02 (g : Fin 15 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 15) det04Term1Row02 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [2]*SparsePolynomial.eval (gapValues g) det04Pair1 := by
  rw [← SparsePolynomial.eval_decodeCubic, det04Term1Row02_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det04Term1Row03 : CoefficientMerge.Poly := [(nat_lit 258, Int.negSucc (nat_lit 0)), (nat_lit 273, Int.negSucc (nat_lit 0)), (nat_lit 274, Int.negSucc (nat_lit 0)), (nat_lit 275, Int.negSucc (nat_lit 0)), (nat_lit 276, Int.negSucc (nat_lit 0)), (nat_lit 277, Int.negSucc (nat_lit 0)), (nat_lit 278, Int.negSucc (nat_lit 0)), (nat_lit 279, Int.negSucc (nat_lit 0)), (nat_lit 483, Int.negSucc (nat_lit 0)), (nat_lit 498, Int.negSucc (nat_lit 1)), (nat_lit 499, Int.negSucc (nat_lit 1)), (nat_lit 500, Int.negSucc (nat_lit 1)), (nat_lit 501, Int.negSucc (nat_lit 1)), (nat_lit 502, Int.negSucc (nat_lit 1)), (nat_lit 503, Int.negSucc (nat_lit 1)), (nat_lit 504, Int.negSucc (nat_lit 1)), (nat_lit 505, Int.negSucc (nat_lit 0)), (nat_lit 506, Int.negSucc (nat_lit 0)), (nat_lit 723, Int.negSucc (nat_lit 0)), (nat_lit 724, Int.negSucc (nat_lit 1)), (nat_lit 725, Int.negSucc (nat_lit 1)), (nat_lit 726, Int.negSucc (nat_lit 1)), (nat_lit 727, Int.negSucc (nat_lit 1)), (nat_lit 728, Int.negSucc (nat_lit 1)), (nat_lit 729, Int.negSucc (nat_lit 1)), (nat_lit 730, Int.negSucc (nat_lit 0)), (nat_lit 731, Int.negSucc (nat_lit 0)), (nat_lit 739, Int.negSucc (nat_lit 0)), (nat_lit 740, Int.negSucc (nat_lit 1)), (nat_lit 741, Int.negSucc (nat_lit 1)), (nat_lit 742, Int.negSucc (nat_lit 1)), (nat_lit 743, Int.negSucc (nat_lit 1)), (nat_lit 744, Int.negSucc (nat_lit 1)), (nat_lit 745, Int.negSucc (nat_lit 0)), (nat_lit 746, Int.negSucc (nat_lit 0)), (nat_lit 755, Int.negSucc (nat_lit 0)), (nat_lit 756, Int.negSucc (nat_lit 1)), (nat_lit 757, Int.negSucc (nat_lit 1)), (nat_lit 758, Int.negSucc (nat_lit 1)), (nat_lit 759, Int.negSucc (nat_lit 1)), (nat_lit 760, Int.negSucc (nat_lit 0)), (nat_lit 761, Int.negSucc (nat_lit 0)), (nat_lit 771, Int.negSucc (nat_lit 0)), (nat_lit 772, Int.negSucc (nat_lit 1)), (nat_lit 773, Int.negSucc (nat_lit 1)), (nat_lit 774, Int.negSucc (nat_lit 1)), (nat_lit 775, Int.negSucc (nat_lit 0)), (nat_lit 776, Int.negSucc (nat_lit 0)), (nat_lit 787, Int.negSucc (nat_lit 0)), (nat_lit 788, Int.negSucc (nat_lit 1)), (nat_lit 789, Int.negSucc (nat_lit 1)), (nat_lit 790, Int.negSucc (nat_lit 0)), (nat_lit 791, Int.negSucc (nat_lit 0)), (nat_lit 803, Int.negSucc (nat_lit 0)), (nat_lit 804, Int.negSucc (nat_lit 1)), (nat_lit 805, Int.negSucc (nat_lit 0)), (nat_lit 806, Int.negSucc (nat_lit 0)), (nat_lit 819, Int.negSucc (nat_lit 0)), (nat_lit 820, Int.negSucc (nat_lit 0)), (nat_lit 821, Int.negSucc (nat_lit 0))]
theorem det04Term1Row03_decode : SparsePolynomial.decodeCubic 15 det04Term1Row03 = SparsePolynomial.monoTimes [3] (-1 : Int) det04Pair1 := by decide +kernel
theorem eval_det04Term1Row03 (g : Fin 15 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 15) det04Term1Row03 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [3]*SparsePolynomial.eval (gapValues g) det04Pair1 := by
  rw [← SparsePolynomial.eval_decodeCubic, det04Term1Row03_decode, SparsePolynomial.eval_monoTimes]
  norm_num

end APPT.Finite15
