import Entry005.ActualFiniteEnclosingCap
import Entry005.ActualFiniteEnclosingRadialCap
import Entry005.ActualNormalizedDirectionalRoundness
import Entry005.ActualSupportFirstVariationTest
import Entry005.CenteredAtomCorrection
import Entry005.ConditionalPyramidMomentBridge
import Entry005.FiniteHalfspaceCenteredCorrection
import Entry005.FiniteMinkowskiScaleGate
import Entry005.FiniteRadialSupportScale
import Entry005.MainTarget
import Entry005.OriginalRadialScale
import Entry005.PolarSimplexConstruction
import Entry005.ProjectionScaleAssembly
import Entry005.PyramidApproximationLimits
import Entry005.SameWitnessOriginalQBudget
import Entry005.SharpConstantGates
import Entry005.SharpMainRetentionAssembly
import Entry005.SharpUpperMain
import Entry005.SupportScaleCapAssembly
import Entry005.VerifiedPyramidMomentBridge
set_option pp.universes true
#check Entry005.actual_body_affine_first_moment_tendsto_of_compact_limit
#print axioms Entry005.actual_body_affine_first_moment_tendsto_of_compact_limit
#check Entry005.actual_body_assignment_volume_scale_of_finite_minkowski
#print axioms Entry005.actual_body_assignment_volume_scale_of_finite_minkowski
#check Entry005.actual_body_enclosing_support_height_assignment_test_bound
#print axioms Entry005.actual_body_enclosing_support_height_assignment_test_bound
#check Entry005.actual_body_enclosing_support_height_assignment_test_bounds
#print axioms Entry005.actual_body_enclosing_support_height_assignment_test_bounds
#check Entry005.actual_body_horizontal_first_moment_pos_of_compact_limit
#print axioms Entry005.actual_body_horizontal_first_moment_pos_of_compact_limit
#check Entry005.actual_body_original_scale_of_strong_same_assignment
#print axioms Entry005.actual_body_original_scale_of_strong_same_assignment
#check Entry005.actual_body_same_assignment_linear_volume_bound
#print axioms Entry005.actual_body_same_assignment_linear_volume_bound
#check Entry005.actual_body_scale_of_same_assignment_budget
#print axioms Entry005.actual_body_scale_of_same_assignment_budget
#check Entry005.actual_body_support_height_facet_sum_tendsto
#print axioms Entry005.actual_body_support_height_facet_sum_tendsto
#check Entry005.actual_body_support_height_test_integral_tendsto
#print axioms Entry005.actual_body_support_height_test_integral_tendsto
#check Entry005.actual_body_volume_ratio_le_linear_support_test
#print axioms Entry005.actual_body_volume_ratio_le_linear_support_test
#check Entry005.actual_body_volume_ratio_le_support_test_pow_of_finite_minkowski
#print axioms Entry005.actual_body_volume_ratio_le_support_test_pow_of_finite_minkowski
#check Entry005.actual_cap_bound_of_scale_and_brightness
#print axioms Entry005.actual_cap_bound_of_scale_and_brightness
#check Entry005.actual_cap_of_same_assignment_and_finite_minkowski
#print axioms Entry005.actual_cap_of_same_assignment_and_finite_minkowski
#check Entry005.actual_entryDefect_nonnegative_of_prescribed_maximum
#print axioms Entry005.actual_entryDefect_nonnegative_of_prescribed_maximum
#check Entry005.actual_finite_enclosing_body_same_assignment_cap
#print axioms Entry005.actual_finite_enclosing_body_same_assignment_cap
#check Entry005.actual_finite_enclosing_body_strong_same_assignment_cap
#print axioms Entry005.actual_finite_enclosing_body_strong_same_assignment_cap
#check Entry005.actual_polar_enclosing_simplex
#print axioms Entry005.actual_polar_enclosing_simplex
#check Entry005.actual_polar_enclosing_simplex_original_radius
#print axioms Entry005.actual_polar_enclosing_simplex_original_radius
#check Entry005.actual_projection_deficit_of_scale_and_brightness
#print axioms Entry005.actual_projection_deficit_of_scale_and_brightness
#check Entry005.actual_same_limit_anchor_defect_entryDefect
#print axioms Entry005.actual_same_limit_anchor_defect_entryDefect
#check Entry005.actual_same_limit_anchor_moment_entryA
#print axioms Entry005.actual_same_limit_anchor_moment_entryA
#check Entry005.assigned_atom_absolute_direction_error
#print axioms Entry005.assigned_atom_absolute_direction_error
#check Entry005.assigned_atom_barycenter_norm_le_cost
#print axioms Entry005.assigned_atom_barycenter_norm_le_cost
#check Entry005.assigned_atom_weights_integral
#print axioms Entry005.assigned_atom_weights_integral
#check Entry005.assigned_atom_weights_probability
#print axioms Entry005.assigned_atom_weights_probability
#check Entry005.bounded_body_volume_le_cube
#print axioms Entry005.bounded_body_volume_le_cube
#check Entry005.centered_atom_mixture_mean
#print axioms Entry005.centered_atom_mixture_mean
#check Entry005.centered_atom_mixture_probability
#print axioms Entry005.centered_atom_mixture_probability
#check Entry005.centered_atom_mixture_test_error
#print axioms Entry005.centered_atom_mixture_test_error
#check Entry005.centered_integral_negative_eq_half_absolute
#print axioms Entry005.centered_integral_negative_eq_half_absolute
#check Entry005.compact_cone_law_support_height_assignment_test_bound
#print axioms Entry005.compact_cone_law_support_height_assignment_test_bound
#check Entry005.compact_support_height_mono
#print axioms Entry005.compact_support_height_mono
#check Entry005.compact_support_height_raw_abs_bound
#print axioms Entry005.compact_support_height_raw_abs_bound
#check Entry005.conditional_actual_body_affine_first_moment_entryA_of_compact_limit
#print axioms Entry005.conditional_actual_body_affine_first_moment_entryA_of_compact_limit
#check Entry005.conditional_actual_body_determinant_defect_entryDefect_of_compact_limit
#print axioms Entry005.conditional_actual_body_determinant_defect_entryDefect_of_compact_limit
#check Entry005.conditional_actual_body_joint_polar_horizontal_assignment_defect
#print axioms Entry005.conditional_actual_body_joint_polar_horizontal_assignment_defect
#check Entry005.conditional_actual_pyramid_projection_formula_of_compact_limit
#print axioms Entry005.conditional_actual_pyramid_projection_formula_of_compact_limit
#check Entry005.conditional_actual_pyramid_volume_formula
#print axioms Entry005.conditional_actual_pyramid_volume_formula
#check Entry005.conditional_halfspace_approximation_pyramid_projection_formula
#print axioms Entry005.conditional_halfspace_approximation_pyramid_projection_formula
#check Entry005.conditional_halfspace_approximation_pyramid_volume_formula
#print axioms Entry005.conditional_halfspace_approximation_pyramid_volume_formula
#check Entry005.euclidean_closed_ball_volume_le_cube
#print axioms Entry005.euclidean_closed_ball_volume_le_cube
#check Entry005.exists_centered_assigned_atom_brightness
#print axioms Entry005.exists_centered_assigned_atom_brightness
#check Entry005.exists_centered_atom_correction
#print axioms Entry005.exists_centered_atom_correction
#check Entry005.exists_correcting_probability_on_same_atoms
#print axioms Entry005.exists_correcting_probability_on_same_atoms
#check Entry005.finite_actual_pyramid_projection_formula_proved
#print axioms Entry005.finite_actual_pyramid_projection_formula_proved
#check Entry005.finite_actual_pyramid_volume_formula_proved
#print axioms Entry005.finite_actual_pyramid_volume_formula_proved
#check Entry005.finite_assignment_error_integrable_of_unit_ball
#print axioms Entry005.finite_assignment_error_integrable_of_unit_ball
#check Entry005.finite_atom_negative_integral_eq_weighted
#print axioms Entry005.finite_atom_negative_integral_eq_weighted
#check Entry005.finite_centered_negative_eq_half_absolute
#print axioms Entry005.finite_centered_negative_eq_half_absolute
#check Entry005.finite_convex_hull_probability_weights
#print axioms Entry005.finite_convex_hull_probability_weights
#check Entry005.finite_dimensional_projection_body_compact
#print axioms Entry005.finite_dimensional_projection_body_compact
#check Entry005.finite_halfspace_assigned_cone_weights
#print axioms Entry005.finite_halfspace_assigned_cone_weights
#check Entry005.finite_halfspace_centered_assignment_brightness
#print axioms Entry005.finite_halfspace_centered_assignment_brightness
#check Entry005.finite_halfspace_radial_support_test_bound
#print axioms Entry005.finite_halfspace_radial_support_test_bound
#check Entry005.finite_halfspace_scaled_radial_cover
#print axioms Entry005.finite_halfspace_scaled_radial_cover
#check Entry005.finite_halfspace_scaled_radial_volume_bound
#print axioms Entry005.finite_halfspace_scaled_radial_volume_bound
#check Entry005.finite_halfspace_support_height_test_integrable
#print axioms Entry005.finite_halfspace_support_height_test_integrable
#check Entry005.finite_halfspace_support_height_test_integral
#print axioms Entry005.finite_halfspace_support_height_test_integral
#check Entry005.finite_halfspace_unit_atom_normalized_brightness_le_half
#print axioms Entry005.finite_halfspace_unit_atom_normalized_brightness_le_half
#check Entry005.finite_probability_test_bounds
#print axioms Entry005.finite_probability_test_bounds
#check Entry005.finite_zero_barycentric_weights_unique
#print axioms Entry005.finite_zero_barycentric_weights_unique
#check Entry005.halfspace_approximation_pyramid_compact
#print axioms Entry005.halfspace_approximation_pyramid_compact
#check Entry005.halfspace_approximation_pyramid_dilation_sandwich
#print axioms Entry005.halfspace_approximation_pyramid_dilation_sandwich
#check Entry005.halfspace_approximation_pyramid_projection_body_volume_tendsto
#print axioms Entry005.halfspace_approximation_pyramid_projection_body_volume_tendsto
#check Entry005.halfspace_approximation_pyramid_volume_tendsto
#print axioms Entry005.halfspace_approximation_pyramid_volume_tendsto
#check Entry005.halfspace_approximation_support_height_test_integral
#print axioms Entry005.halfspace_approximation_support_height_test_integral
#check Entry005.normalized_body_directional_brightness_lower_original
#print axioms Entry005.normalized_body_directional_brightness_lower_original
#check Entry005.normalized_convex_body_cone_directional_roundness
#print axioms Entry005.normalized_convex_body_cone_directional_roundness
#check Entry005.normalized_convex_body_cone_raw_directional_roundness
#print axioms Entry005.normalized_convex_body_cone_raw_directional_roundness
#check Entry005.normalized_maximum_simplex_excess_of_original_cap
#print axioms Entry005.normalized_maximum_simplex_excess_of_original_cap
#check Entry005.normalized_sharp_upper_local
#print axioms Entry005.normalized_sharp_upper_local
#check Entry005.original_Q_absorbs_radial_power
#print axioms Entry005.original_Q_absorbs_radial_power
#check Entry005.original_Q_dominates_strong_assignment_coefficient
#print axioms Entry005.original_Q_dominates_strong_assignment_coefficient
#check Entry005.original_cap_radius_retention_gate
#print axioms Entry005.original_cap_radius_retention_gate
#check Entry005.original_global_scalar_gluing
#print axioms Entry005.original_global_scalar_gluing
#check Entry005.original_local_cap_to_excess_scalar
#print axioms Entry005.original_local_cap_to_excess_scalar
#check Entry005.original_one_le_M
#print axioms Entry005.original_one_le_M
#check Entry005.original_radial_strong_cost_absorption
#print axioms Entry005.original_radial_strong_cost_absorption
#check Entry005.original_roundness_cube_coefficient
#print axioms Entry005.original_roundness_cube_coefficient
#check Entry005.original_sharp_threshold
#print axioms Entry005.original_sharp_threshold
#check Entry005.original_small_error_budget
#print axioms Entry005.original_small_error_budget
#check Entry005.original_small_error_implies_M_budget
#print axioms Entry005.original_small_error_implies_M_budget
#check Entry005.original_threshold_gate
#print axioms Entry005.original_threshold_gate
#check Entry005.polar_vertex_coord_eq_basis_coord
#print axioms Entry005.polar_vertex_coord_eq_basis_coord
#check Entry005.polar_vertex_coord_vertex
#print axioms Entry005.polar_vertex_coord_vertex
#check Entry005.polar_witness_convex_body_coe
#print axioms Entry005.polar_witness_convex_body_coe
#check Entry005.polar_witness_finite_cone_point
#print axioms Entry005.polar_witness_finite_cone_point
#check Entry005.polar_witness_gradient_inner
#print axioms Entry005.polar_witness_gradient_inner
#check Entry005.polar_witness_height_pos
#print axioms Entry005.polar_witness_height_pos
#check Entry005.polar_witness_normal_support_height
#print axioms Entry005.polar_witness_normal_support_height
#check Entry005.polar_witness_normal_unit
#print axioms Entry005.polar_witness_normal_unit
#check Entry005.polar_witness_normals_injective
#print axioms Entry005.polar_witness_normals_injective
#check Entry005.polar_witness_point_ne_zero
#print axioms Entry005.polar_witness_point_ne_zero
#check Entry005.polar_witness_simplex_compact
#print axioms Entry005.polar_witness_simplex_compact
#check Entry005.polar_witness_simplex_contains_body
#print axioms Entry005.polar_witness_simplex_contains_body
#check Entry005.polar_witness_simplex_contains_unit_ball
#print axioms Entry005.polar_witness_simplex_contains_unit_ball
#check Entry005.polar_witness_simplex_halfspaces
#print axioms Entry005.polar_witness_simplex_halfspaces
#check Entry005.polar_witness_simplex_normal_halfspaces
#print axioms Entry005.polar_witness_simplex_normal_halfspaces
#check Entry005.polar_witness_simplex_radius_bound
#print axioms Entry005.polar_witness_simplex_radius_bound
#check Entry005.polar_witness_simplex_support_one
#print axioms Entry005.polar_witness_simplex_support_one
#check Entry005.polar_witness_vertex_inner
#print axioms Entry005.polar_witness_vertex_inner
#check Entry005.polar_witness_vertices_affine_independent
#print axioms Entry005.polar_witness_vertices_affine_independent
#check Entry005.polar_witness_weight_lt_one
#print axioms Entry005.polar_witness_weight_lt_one
#check Entry005.polar_witness_weight_pos
#print axioms Entry005.polar_witness_weight_pos
#check Entry005.power_minus_one_le_bounded_geometric_sum
#print axioms Entry005.power_minus_one_le_bounded_geometric_sum
#check Entry005.projection_difference_of_normalized_brightness
#print axioms Entry005.projection_difference_of_normalized_brightness
#check Entry005.pyramid_apex_mem
#print axioms Entry005.pyramid_apex_mem
#check Entry005.pyramid_base_mem
#print axioms Entry005.pyramid_base_mem
#check Entry005.pyramid_first_moment_entry_scalar_algebra
#print axioms Entry005.pyramid_first_moment_entry_scalar_algebra
#check Entry005.pyramid_product_finrank
#print axioms Entry005.pyramid_product_finrank
#check Entry005.pyramid_set_compact
#print axioms Entry005.pyramid_set_compact
#check Entry005.pyramid_set_convex
#print axioms Entry005.pyramid_set_convex
#check Entry005.pyramid_set_dilation_sandwich
#print axioms Entry005.pyramid_set_dilation_sandwich
#check Entry005.pyramid_set_eq_parametric_image
#print axioms Entry005.pyramid_set_eq_parametric_image
#check Entry005.pyramid_set_mono
#print axioms Entry005.pyramid_set_mono
#check Entry005.pyramid_set_subset_dilation
#print axioms Entry005.pyramid_set_subset_dilation
#check Entry005.pyramid_zero_mem
#print axioms Entry005.pyramid_zero_mem
#check Entry005.raw_zero_barycentric_weights_assignment_brightness
#print axioms Entry005.raw_zero_barycentric_weights_assignment_brightness
#check Entry005.same_witness_original_Q_and_round_hull
#print axioms Entry005.same_witness_original_Q_and_round_hull
#check Entry005.scale_increment_of_volume_ratio
#print axioms Entry005.scale_increment_of_volume_ratio
#check Entry005.sharpLocal
#print axioms Entry005.sharpLocal
#check Entry005.sharpMain
#print axioms Entry005.sharpMain
#check Entry005.sharpMain_of_local_and_actual_coarse
#print axioms Entry005.sharpMain_of_local_and_actual_coarse
#check Entry005.strong_ratio_assignment_le_original_Q_budget
#print axioms Entry005.strong_ratio_assignment_le_original_Q_budget
#check Entry005.support_height_assignment_pointwise_bound
#print axioms Entry005.support_height_assignment_pointwise_bound
#check Entry005.unit_ball_support_height_assignment_test_bound
#print axioms Entry005.unit_ball_support_height_assignment_test_bound
#check Entry005.unit_ball_support_height_test_integrable
#print axioms Entry005.unit_ball_support_height_test_integrable
#check Entry005.unit_increment_power_bound
#print axioms Entry005.unit_increment_power_bound
#check Entry005.unit_projection_ball_volume_lower_original
#print axioms Entry005.unit_projection_ball_volume_lower_original
#check Entry005.zero_barycentric_weights_assigned_brightness
#print axioms Entry005.zero_barycentric_weights_assigned_brightness
#check Entry005.polarWitnessBasis
#print axioms Entry005.polarWitnessBasis
#check Entry005.polarWitnessWeight
#print axioms Entry005.polarWitnessWeight
#check Entry005.polarWitnessGradient
#print axioms Entry005.polarWitnessGradient
#check Entry005.polarWitnessVertex
#print axioms Entry005.polarWitnessVertex
#check Entry005.polarVertexBasis
#print axioms Entry005.polarVertexBasis
#check Entry005.polarVertexCoord
#print axioms Entry005.polarVertexCoord
#check Entry005.polarWitnessSimplex
#print axioms Entry005.polarWitnessSimplex
#check Entry005.polarWitnessNormal
#print axioms Entry005.polarWitnessNormal
#check Entry005.polarWitnessHeight
#print axioms Entry005.polarWitnessHeight
#check Entry005.polarWitnessConvexBody
#print axioms Entry005.polarWitnessConvexBody

set_option pp.universes false in
#check (Entry005.sharpMain : Entry005.sharpMainGoal)
set_option pp.universes false in
#check (Entry005.sharpMain : Entry005.MainTarget)
example : Entry005.sharpLocalGoal := Entry005.sharpLocal
example : Entry005.sharpMainGoal := Entry005.sharpMain
example : Entry005.MainTarget := Entry005.sharpMain
