import BapatMarkedInversions
import BapatTwoRowCofactor
import BapatColorTransport
import BapatColorExpansion
import BapatPermanentFischer
import BapatMixedFischer
import BapatDefs
import BapatReality
import BapatContinuity
import BapatOriginalStatement
import BapatRankTwoIdentity
import BapatWedgeRecurrence
import BapatExactCoefficients
import BapatExactStateBridge
import BapatN200Data
import BapatN200Matrix
import BapatN200Trace0
import BapatN200Trace1
import BapatN200Trace2
import BapatN200Trace3
import BapatN200Trace
import BapatN200Counterexample
import Lean.Replay
import Lean

open Lean Elab Command
set_option maxRecDepth 100000
set_option maxHeartbeats 0

-- Adapted from the repository's continuum proof-closure replay.
-- Missing constants fail closed. Inductive companions are included.
partial def collect (env : Environment) (todo : List Name)
    (seen : Std.HashMap Name ConstantInfo) : Except String (Std.HashMap Name ConstantInfo) :=
  match todo with
  | [] => .ok seen
  | n :: rest =>
    if seen.contains n then collect env rest seen
    else match env.find? n with
    | none => .error s!"Missing dependency {n}"
    | some ci =>
      let extra := match ci with
        | .inductInfo v => v.all ++ v.ctors
        | .ctorInfo v => [v.induct]
        | .recInfo v => v.all
        | .defnInfo v => v.all
        | .thmInfo v => v.all
        | .opaqueInfo v => v.all
        | .quotInfo _ => [``Eq]
        | _ => []
      collect env (extra ++ ci.getUsedConstantsAsSet.toList ++ rest) (seen.insert n ci)

run_cmd do
  let env := (← getEnv).setExporting false
  let roots := [(Name.str (Name.str Name.anonymous "BapatFischer") "ColorTransport"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "card_colorTransport"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "card_colorTransport_finset"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "card_colorTransport_of_eq"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "card_colorTransport_of_ne"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "card_finset_map_fiber"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "coeff_twoColorProduct"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "coeff_twoColorProduct_filter"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "coeff_twoColorProduct_star"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "colorTransportEquiv"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "colorWeight"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "colorWeight_map"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "colorWeight_star"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "finset_map_eq_iff_colorTransport"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "fischerNormSq"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "fischerNormSq_nonneg"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "fischerPair"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "fischerPair_C_mul_left"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "fischerPair_C_mul_right"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "fischerPair_self"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "fischerPair_sum_left"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "fischerPair_sum_right"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "mixedPermanent"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "mixedPermanent_eq_permanent"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "mixedPermanent_gram"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "mixedPermanent_twoColor"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "permanent_rankTwo_gram"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "permanent_twoColor"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "permanent_twoColor_expand"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "sum_colorWeight_by_card"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "sum_perm_colorWeight"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "twoColorProduct"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "twoColorProduct_comp"),
    (Name.str (Name.str Name.anonymous "BapatFischer") "twoColorProduct_expand"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "BapatConjecture"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "FSeq"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "FSeq_eq_natF"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "FSeq_eq_twoColorProduct"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "OriginalBapatConjecture"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "SSeq"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "SSeq_eq_natS"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "SSeq_eq_wedgePolynomial"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "bapatConjecture_false_of_psd_derivative_neg"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "continuous_perturb_derivative_one"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "exists_interior_decrease_of_derivative_one_neg"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "exists_posDef_interior_counterexample_of_psd_derivative_neg"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "gram"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "gram_isHermitian"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "gram_minor"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "gram_posSemidef"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "gram_twoRowCofactor"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "inversions"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "inversions_symm"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "linearFactor"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natF"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natF_derivative"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natF_euler"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natF_succ"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natF_zero"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natRemaining"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natRemaining_succ_last"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natRemaining_succ_old"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natS"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natS_succ"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natS_succ_split"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natS_zero"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natSingleRemaining"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "natSingleRemaining_eq_erase"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "not_monotoneOn_of_derivative_one_neg"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "originalBapatConjecture_false_of_psd_derivative_neg"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "permanentSum_eq_permanent"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "permutationWeight_star_of_isHermitian"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "perturb"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "perturb_not_isDiag"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "perturb_posDef"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "perturb_zero"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "prod_erase_as_ite"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "prod_erase_two_as_ite"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "qPermanent"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "qPermanent_eq_ofReal_eval"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "qPermanent_star_of_isHermitian"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "rankTwo_fischer_inversion_identity"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "realQPolynomial"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "realQPolynomial_derivative_fischer"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "realQPolynomial_derivative_one"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "realQPolynomial_eval"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "remainingPolynomial"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "remainingPolynomial_eq_erased_product"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "remainingPolynomial_fin_eq_natRemaining"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "twoColorProduct_fin_eq_natF"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "wedge"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "wedgePolynomial"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "wedgePolynomial_fin_eq_natS"),
    (Name.str (Name.str Name.anonymous "BapatRankTwo") "wedgePolynomial_pair"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "coeff_twoColorProduct") "_simp_1_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorTransportEquiv") "_proof_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorTransportEquiv") "_proof_2"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorTransportEquiv") "_proof_3"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorTransportEquiv") "_proof_4"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorTransportEquiv") "_proof_5"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorTransportEquiv") "_proof_6"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorTransportEquiv") "_proof_7"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorTransportEquiv") "_proof_8"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorWeight") "congr_simp"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "colorWeight") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "fischerNormSq") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "fischerPair") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatFischer") "permanent_twoColor") "_simp_1_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "Coeffs"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "GI"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "add"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "coeff_interpret"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "derivative"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "derivativeAux"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "derivative_negative_of_gap"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "fischerInt"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "fischerInt_correct"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "fischerInt_state_f"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "fischerInt_state_s"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_add"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_derivative"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_derivativeAux"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_mulLinear"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_neg"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_nil"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_sStep"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_scale"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_shift"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_state"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_state_f"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_state_s"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret_sub"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "mulLinear"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "neg"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "sStep"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "scale"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "shift"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "squareAbs"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "squareAbs_toComplex"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "state"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "sub"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "toComplex"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "vectorAt"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "FSeq") "_f"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "FSeq") "_sunfold"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "FSeq") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "FSeq") "eq_2"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "FSeq") "eq_def"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "FSeq") "match_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "TwoPointComplement"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "ascending_images_eq_cofactor_sum"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint_complement"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint_first"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint_second"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "instFintypePerm_bapatMarkedInversions"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "instFintypePerm_bapatTwoRowCofactor"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "inversionPairSum"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "inversionPairSum_eq_swap"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "marked_inversion_cofactor_identity"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "marked_inversion_determinant_identity"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "originalInversions"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "originalInversions_cast"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "originalPairs"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "originalPairs_card"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "permanentSum"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "permanentSum_split_images"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "permanentSum_sub_two_inversionPairSum"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "permutationWeight"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "permutationWeight_split"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "permutationWeight_sub_swapRowsPerm"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "remainingWeight"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "remainingWeight_eq_complement_product"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "remainingWeight_swapRowsPerm"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "restrictTwoPoint"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "restrictTwoPoint_apply"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "swapRowsEquiv"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "swapRowsPerm"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "swapRowsPerm_apply"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "swapRowsPerm_twice"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointComplement_card"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointFiberEquiv"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoRowCofactor"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoRowCofactor_eq_equiv_sum"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "weightedInversionSum"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "weightedInversionSum_eq_sum_pairs"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "a"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "b"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "bapatConjecture_false"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_000"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_001"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_002"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_003"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_004"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_005"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_006"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_007"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_008"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_009"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_010"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_011"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_012"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_013"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_014"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_015"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_016"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_017"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_018"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_019"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_020"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_021"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_022"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_023"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_024"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_025"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_026"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_027"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_028"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_029"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_030"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_031"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_032"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_033"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_034"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_035"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_036"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_037"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_038"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_039"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_040"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_041"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_042"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_043"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_044"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_045"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_046"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_047"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_048"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_049"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_050"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_051"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_052"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_053"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_054"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_055"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_056"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_057"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_058"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_059"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_060"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_061"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_062"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_063"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_064"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_065"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_066"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_067"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_068"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_069"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_070"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_071"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_072"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_073"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_074"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_075"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_076"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_077"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_078"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_079"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_080"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_081"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_082"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_083"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_084"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_085"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_086"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_087"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_088"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_089"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_090"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_091"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_092"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_093"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_094"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_095"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_096"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_097"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_098"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_099"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_100"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_101"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_102"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_103"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_104"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_105"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_106"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_107"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_108"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_109"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_110"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_111"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_112"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_113"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_114"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_115"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_116"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_117"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_118"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_119"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_120"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_121"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_122"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_123"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_124"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_125"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_126"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_127"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_128"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_129"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_130"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_131"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_132"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_133"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_134"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_135"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_136"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_137"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_138"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_139"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_140"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_141"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_142"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_143"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_144"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_145"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_146"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_147"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_148"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_149"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_150"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_151"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_152"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_153"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_154"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_155"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_156"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_157"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_158"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_159"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_160"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_161"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_162"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_163"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_164"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_165"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_166"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_167"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_168"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_169"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_170"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_171"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_172"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_173"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_174"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_175"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_176"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_177"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_178"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_179"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_180"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_181"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_182"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_183"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_184"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_185"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_186"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_187"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_188"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_189"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_190"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_191"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_192"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_193"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_194"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_195"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_196"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_197"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_198"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_199"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "checkpoint_200"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "explicit_counterexample"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "matrix"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "matrix_derivative_negative"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "matrix_not_isDiag"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "matrix_posSemidef"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "matrix_zero_one"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "norm_gap_positive"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "originalBapatConjecture_false"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "permanentNorm"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "perturb_matrix_not_isDiag"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "perturb_matrix_posDef"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_000"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_001"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_002"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_003"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_004"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_005"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_006"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_007"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_008"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_009"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_010"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_011"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_012"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_013"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_014"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_015"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_016"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_017"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_018"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_019"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_020"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_021"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_022"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_023"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_024"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_025"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_026"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_027"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_028"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_029"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_030"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_031"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_032"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_033"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_034"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_035"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_036"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_037"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_038"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_039"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_040"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_041"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_042"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_043"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_044"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_045"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_046"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_047"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_048"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_049"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_050"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_051"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_052"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_053"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_054"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_055"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_056"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_057"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_058"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_059"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_060"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_061"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_062"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_063"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_064"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_065"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_066"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_067"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_068"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_069"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_070"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_071"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_072"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_073"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_074"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_075"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_076"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_077"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_078"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_079"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_080"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_081"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_082"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_083"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_084"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_085"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_086"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_087"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_088"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_089"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_090"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_091"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_092"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_093"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_094"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_095"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_096"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_097"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_098"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_099"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_100"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_101"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_102"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_103"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_104"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_105"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_106"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_107"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_108"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_109"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_110"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_111"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_112"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_113"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_114"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_115"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_116"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_117"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_118"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_119"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_120"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_121"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_122"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_123"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_124"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_125"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_126"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_127"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_128"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_129"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_130"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_131"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_132"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_133"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_134"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_135"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_136"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_137"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_138"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_139"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_140"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_141"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_142"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_143"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_144"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_145"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_146"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_147"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_148"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_149"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_150"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_151"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_152"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_153"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_154"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_155"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_156"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_157"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_158"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_159"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_160"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_161"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_162"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_163"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_164"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_165"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_166"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_167"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_168"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_169"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_170"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_171"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_172"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_173"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_174"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_175"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_176"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_177"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_178"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_179"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_180"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_181"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_182"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_183"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_184"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_185"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_186"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_187"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_188"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_189"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_190"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_191"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_192"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_193"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_194"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_195"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_196"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_197"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_198"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_199"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_200"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "vectors"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "vectors_length"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "wedgeNorm"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "SSeq") "_f"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "SSeq") "_sunfold"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "SSeq") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "SSeq") "eq_2"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "SSeq") "eq_def"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "gram") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "inversions") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "inversions_symm") "_simp_1_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "inversions_symm") "_simp_1_2"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "linearFactor") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "natF") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "natF_euler") "_simp_1_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "natRemaining") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "natRemaining_succ_last") "_simp_1_2"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "natS") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "natS_succ_split") "_proof_1_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "natSingleRemaining") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "perturb") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "prod_erase_as_ite") "_simp_1_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "prod_erase_two_as_ite") "_simp_1_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "prod_erase_two_as_ite") "_simp_1_2"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "prod_erase_two_as_ite") "_simp_1_3"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "prod_erase_two_as_ite") "_simp_1_4"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "qPermanent") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "realQPolynomial") "eq_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "realQPolynomial_eval") "_simp_1_3"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "remainingPolynomial_eq_erased_product") "_simp_1_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "remainingPolynomial_fin_eq_natRemaining") "_simp_1_1"),
    (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "wedge") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "add") "_f"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "add") "_sunfold"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "add") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "add") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "add") "eq_3"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "add") "eq_def"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "add") "match_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "derivative") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "derivativeAux") "_f"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "derivativeAux") "_sunfold"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "derivativeAux") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "derivativeAux") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "derivativeAux") "eq_def"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "fischerInt") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret") "_f"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret") "_sunfold"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret") "eq_def"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "interpret") "match_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "mulLinear") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "neg") "_f"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "neg") "_sunfold"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "neg") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "neg") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "neg") "eq_def"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "sStep") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "scale") "_f"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "scale") "_sunfold"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "scale") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "scale") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "scale") "eq_def"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "shift") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "squareAbs") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "state") "_f"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "state") "_sunfold"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "state") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "state") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "state") "eq_def"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "state") "match_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "sub") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "toComplex") "_proof_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "Exact") "toComplex") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "ascending_images_eq_cofactor_sum") "_simp_1_3"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "ascending_images_eq_cofactor_sum") "_simp_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint") "_proof_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint") "_proof_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint") "_proof_3"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint") "_proof_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint") "_proof_5"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint") "congr_simp"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "extendTwoPoint") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "originalInversions") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "originalPairs") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "permutationWeight") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "remainingWeight") "congr_simp"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "remainingWeight_eq_complement_product") "_simp_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "restrictTwoPoint") "_proof_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "restrictTwoPoint") "_proof_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "restrictTwoPoint") "_proof_3"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "restrictTwoPoint") "_proof_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "restrictTwoPoint") "_proof_5"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "restrictTwoPoint") "_proof_6"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "restrictTwoPoint") "congr_simp"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "swapRowsEquiv") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointComplement_card") "_proof_1_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointComplement_card") "_simp_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointFiberEquiv") "_proof_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointFiberEquiv") "_proof_2"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointFiberEquiv") "_proof_3"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointFiberEquiv") "_proof_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointFiberEquiv") "_proof_5"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointFiberEquiv") "_proof_6"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointFiberEquiv") "_proof_7"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "twoPointFiberEquiv") "_proof_8"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "MarkedInversions") "weightedInversionSum") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "norm_gap_positive") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_001") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_002") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_003") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_004") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_005") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_006") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_007") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_008") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_009") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_010") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_011") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_012") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_013") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_014") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_015") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_016") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_017") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_018") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_019") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_020") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_021") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_022") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_023") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_024") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_025") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_026") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_027") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_028") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_029") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_030") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_031") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_032") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_033") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_034") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_035") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_036") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_037") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_038") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_039") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_040") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_041") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_042") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_043") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_044") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_045") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_046") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_047") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_048") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_049") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_050") "_proof_1_4"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_051") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_052") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_053") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_054") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_055") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_056") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_057") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_058") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_059") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_060") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_061") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_062") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_063") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_064") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_065") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_066") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_067") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_068") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_069") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_070") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_071") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_072") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_073") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_074") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_075") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_076") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_077") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_078") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_079") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_080") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_081") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_082") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_083") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_084") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_085") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_086") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_087") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_088") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_089") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_090") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_091") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_092") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_093") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_094") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_095") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_096") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_097") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_098") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_099") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_100") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_101") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_102") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_103") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_104") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_105") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_106") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_107") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_108") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_109") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_110") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_111") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_112") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_113") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_114") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_115") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_116") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_117") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_118") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_119") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_120") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_121") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_122") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_123") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_124") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_125") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_126") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_127") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_128") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_129") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_130") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_131") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_132") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_133") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_134") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_135") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_136") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_137") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_138") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_139") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_140") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_141") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_142") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_143") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_144") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_145") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_146") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_147") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_148") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_149") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_150") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_151") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_152") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_153") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_154") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_155") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_156") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_157") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_158") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_159") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_160") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_161") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_162") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_163") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_164") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_165") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_166") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_167") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_168") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_169") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_170") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_171") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_172") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_173") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_174") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_175") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_176") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_177") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_178") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_179") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_180") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_181") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_182") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_183") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_184") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_185") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_186") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_187") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_188") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_189") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_190") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_191") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_192") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_193") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_194") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_195") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_196") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_197") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_198") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_199") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str Name.anonymous "BapatRankTwo") "N200") "state_eq_200") "_proof_1_1"),
    (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatWedgeRecurrence") 0) "BapatRankTwo") "FSeq") "match_1") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatWedgeRecurrence") 0) "BapatRankTwo") "FSeq") "match_1") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatWedgeRecurrence") 0) "BapatRankTwo") "FSeq") "match_1") "splitter"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactCoefficients") 0) "BapatRankTwo") "Exact") "add") "match_1") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactCoefficients") 0) "BapatRankTwo") "Exact") "add") "match_1") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactCoefficients") 0) "BapatRankTwo") "Exact") "add") "match_1") "eq_3"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactCoefficients") 0) "BapatRankTwo") "Exact") "add") "match_1") "splitter"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactCoefficients") 0) "BapatRankTwo") "Exact") "interpret") "match_1") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactCoefficients") 0) "BapatRankTwo") "Exact") "interpret") "match_1") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactCoefficients") 0) "BapatRankTwo") "Exact") "interpret") "match_1") "splitter"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactStateBridge") 0) "BapatRankTwo") "Exact") "state") "match_1") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactStateBridge") 0) "BapatRankTwo") "Exact") "state") "match_1") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatExactStateBridge") 0) "BapatRankTwo") "Exact") "state") "match_1") "splitter"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatN200Trace0") 0) "BapatRankTwo") "Exact") "state") "match_1") "eq_1"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatN200Trace0") 0) "BapatRankTwo") "Exact") "state") "match_1") "eq_2"),
    (Name.str (Name.str (Name.str (Name.str (Name.str (Name.num (Name.str (Name.str Name.anonymous "_private") "BapatN200Trace0") 0) "BapatRankTwo") "Exact") "state") "match_1") "splitter")]
  let modules : List String := ["BapatMarkedInversions", "BapatTwoRowCofactor", "BapatColorTransport", "BapatColorExpansion", "BapatPermanentFischer", "BapatMixedFischer", "BapatDefs", "BapatReality", "BapatContinuity", "BapatOriginalStatement", "BapatRankTwoIdentity", "BapatWedgeRecurrence", "BapatExactCoefficients", "BapatExactStateBridge", "BapatN200Data", "BapatN200Matrix", "BapatN200Trace0", "BapatN200Trace1", "BapatN200Trace2", "BapatN200Trace3", "BapatN200Trace", "BapatN200Counterexample"]
  let owned := env.constants.fold (init := #[]) fun acc n _ =>
    match env.getModuleIdxFor? n with
    | none => acc
    | some i => if modules.contains env.header.moduleNames[i.toNat]!.toString
                then acc.push n else acc
  unless owned.size == roots.length && owned.all (fun n => roots.contains n) do
    throwError "Owned declaration inventory differs from actual imported sources"
  let cs ← match collect env roots {} with
    | .ok cs => pure cs
    | .error msg => throwError msg
  for (n, ci) in cs.toList do
    if ci.isUnsafe || ci.isPartial then throwError "Unsafe/partial dependency {n}"
    if ci.isAxiom then
      unless [``propext, ``Classical.choice, ``Quot.sound].contains n do
        throwError "Unexpected axiom {n}"
  let base ← mkEmptyEnvironment 0
  let verified ← base.toKernelEnv.replay cs
  for root in roots do
    let some original := env.find? root | throwError "Original root missing {root}"
    let some checked := verified.find? root | throwError "Replayed root missing {root}"
    unless original.type == checked.type && original.levelParams == checked.levelParams do
      throwError "Changed type/levels {root}"
  logInfo m!"EMPTY_KERNEL_REPLAY_PASS {cs.size} declarations; {roots.length} roots; trust level zero"
