import Mxym

set_option pp.funBinderTypes true

#check Mxym.BalancedRecursion.shifted_dimension
#check Mxym.BalancedRecursion.invariant_closed_form
#check Mxym.BalancedRecursion.dimension_binary
#check Mxym.BalancedRecursion.winning_dimension_level_six
#check Mxym.BalancedRecursion.winning_invariant_level_six
#check Mxym.Determinant.cofactor_vector_relation
#check Mxym.Determinant.mapped_cofactor_relation
#check Mxym.Determinant.cofactor_balance_of_normalized_columns
#check Mxym.Determinant.normalized_sign_average_bound
#check Mxym.Determinant.normalized_sign_average_equality_iff
#check Mxym.Determinant.lift_expansion
#check Mxym.Determinant.horizontal_cofactor_relation
#check Mxym.Determinant.sign_cancellation
#check Mxym.Determinant.sign_average_eq
#check Mxym.Determinant.balanced_sign_average_bound
#check Mxym.Determinant.balanced_sign_average_equality_iff
#check Mxym.FiniteDefect.mean_decomposition
#check Mxym.FiniteDefect.absolute_decomposition
#check Mxym.FiniteDefect.defect_identity
#check Mxym.FiniteDefect.finite_jensen
#check Mxym.FiniteDefect.defect_lower_bound
#check Mxym.FiniteDefect.strict_of_opposite_signs
#check Mxym.FiniteDefect.positive_mass_eq_zero_iff
#check Mxym.FiniteDefect.negative_mass_eq_zero_iff
#check Mxym.FiniteDefect.finite_jensen_eq_iff
#check Mxym.NormedBalance.coefficient_balance
#check Mxym.NormedBalance.rademacher_bound
#check Mxym.NormedBalance.rademacher_equality_iff
#check Mxym.Rademacher.abs_sign
#check Mxym.Rademacher.sign_not
#check Mxym.Rademacher.sign_space_card
#check Mxym.Rademacher.mean_nonneg
#check Mxym.Rademacher.mean_smul
#check Mxym.Rademacher.convex_mean
#check Mxym.Rademacher.continuous_mean
#check Mxym.Rademacher.abs_pair
#check Mxym.Rademacher.mean_eq_of_dominant
#check Mxym.Rademacher.compact_balancedPolytope
#check Mxym.Rademacher.convex_balancedPolytope
#check Mxym.Rademacher.extreme_has_half
#check Mxym.Rademacher.normalized_bound
#check Mxym.Rademacher.mean_abs
#check Mxym.Rademacher.mean_zero
#check Mxym.Rademacher.balanced_bound
#check Mxym.Rademacher.mean_eq_half_of_half_mass
#check Mxym.Rademacher.normalized_defect_lower_bound
#check Mxym.Rademacher.normalized_defect_lower_bound_or_zero
#check Mxym.Rademacher.mean_reindex
#check Mxym.Rademacher.mean_sum_zero
#check Mxym.Rademacher.mean_restrict
#check Mxym.Rademacher.sum_signs_succ
#check Mxym.Rademacher.mean_three_nonneg
#check Mxym.Rademacher.mean_four_quarters
#check Mxym.Rademacher.normalized_strict_positive
#check Mxym.Rademacher.restrict_balanced
#check Mxym.Rademacher.normalized_strict
#check Mxym.Rademacher.normalized_small_finite
#check Mxym.Rademacher.normalized_small_support
#check Mxym.Rademacher.normalized_equality_iff
#check Mxym.Rademacher.balanced_equality_iff
#check Mxym.Transport.signed_square
#check Mxym.Transport.signed_square_eq_iff
#check Mxym.Transport.intermediate_square
#check Mxym.Transport.three_term_square
#check Mxym.StochasticRigidity.abs_det_le_column_l1_product
#check Mxym.StochasticRigidity.abs_det_le_column_max
#check Mxym.StochasticRigidity.column_l1_distance
#check Mxym.StochasticRigidity.abs_det_le_of_shared_row
#check Mxym.StochasticRigidity.near_permutation_sharp
#check Mxym.StochasticRigidity.near_permutation
#check Mxym.StochasticRigidity.exact_permutation
#check OAI.Paper092.twice_sum_negative_eq_sum_abs
#check OAI.Paper092.simplex_constant_product_ratio
#check OAI.Paper092.dimension_twenty_ratio
#check OAI.Paper092.dimension_twenty_strict
#check Entry005.euclidean_unit_ball_cube
#check Entry005.unit_ball_cube
#check Entry005.closest_support
#check Entry005.cap_ball
#check Entry005.cap_measure_gain
#check Entry005.nested_body_cap_gain
#check Entry005.R0_pos
#check Entry005.b_pos
#check Entry005.M_pos
#check Entry005.Q_pos
#check Entry005.L_pos
#check Entry005.J_pos
#check Entry005.rSharp_pos
#check Entry005.eSharp_pos
#check Entry005.aSharp_pos
#check Entry005.gSharp_pos
#check Entry005.project_body_mono
#check Entry005.project_body_unit_ball
#check Entry005.project_body_outer_ball
#check Entry005.inner_project
#check Entry005.exists_perpendicular_unit
#check Entry005.hyperplane_dimension
#check Entry005.projection_cap_gain
#check Entry005.projection_cap_cube_gain
#check Entry005.exists_projection_cap
#check Entry005.hausdorff_from_projection_deficit
