import APPT.Finite12Sparse.Det00Pair1
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
open scoped BigOperators
namespace APPT.Finite12
open SparsePolynomial

def det00Term1Row04 : CoefficientMerge.Poly := [(nat_lit 172, Int.negSucc (nat_lit 0)), (nat_lit 184, Int.negSucc (nat_lit 0)), (nat_lit 196, Int.negSucc (nat_lit 0)), (nat_lit 197, Int.negSucc (nat_lit 0)), (nat_lit 198, Int.negSucc (nat_lit 0)), (nat_lit 316, Int.negSucc (nat_lit 0)), (nat_lit 328, Int.negSucc (nat_lit 1)), (nat_lit 340, Int.negSucc (nat_lit 1)), (nat_lit 341, Int.negSucc (nat_lit 1)), (nat_lit 342, Int.negSucc (nat_lit 1)), (nat_lit 343, Int.negSucc (nat_lit 0)), (nat_lit 472, Int.negSucc (nat_lit 0)), (nat_lit 484, Int.negSucc (nat_lit 1)), (nat_lit 485, Int.negSucc (nat_lit 1)), (nat_lit 486, Int.negSucc (nat_lit 1)), (nat_lit 487, Int.negSucc (nat_lit 0)), (nat_lit 628, Int.negSucc (nat_lit 0)), (nat_lit 629, Int.negSucc (nat_lit 1)), (nat_lit 630, Int.negSucc (nat_lit 1)), (nat_lit 631, Int.negSucc (nat_lit 0)), (nat_lit 641, Int.negSucc (nat_lit 0)), (nat_lit 642, Int.negSucc (nat_lit 1)), (nat_lit 643, Int.negSucc (nat_lit 0)), (nat_lit 654, Int.negSucc (nat_lit 0)), (nat_lit 655, Int.negSucc (nat_lit 0))]
theorem det00Term1Row04_decode : SparsePolynomial.decodeCubic 12 det00Term1Row04 = SparsePolynomial.monoTimes [4] (-1 : Int) det00Pair1 := by decide +kernel
theorem eval_det00Term1Row04 (g : Fin 12 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 12) det00Term1Row04 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [4]*SparsePolynomial.eval (gapValues g) det00Pair1 := by
  rw [← SparsePolynomial.eval_decodeCubic, det00Term1Row04_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det00Term1Row05 : CoefficientMerge.Poly := [(nat_lit 173, Int.negSucc (nat_lit 0)), (nat_lit 185, Int.negSucc (nat_lit 0)), (nat_lit 197, Int.negSucc (nat_lit 0)), (nat_lit 209, Int.negSucc (nat_lit 0)), (nat_lit 210, Int.negSucc (nat_lit 0)), (nat_lit 317, Int.negSucc (nat_lit 0)), (nat_lit 329, Int.negSucc (nat_lit 1)), (nat_lit 341, Int.negSucc (nat_lit 1)), (nat_lit 353, Int.negSucc (nat_lit 1)), (nat_lit 354, Int.negSucc (nat_lit 1)), (nat_lit 355, Int.negSucc (nat_lit 0)), (nat_lit 473, Int.negSucc (nat_lit 0)), (nat_lit 485, Int.negSucc (nat_lit 1)), (nat_lit 497, Int.negSucc (nat_lit 1)), (nat_lit 498, Int.negSucc (nat_lit 1)), (nat_lit 499, Int.negSucc (nat_lit 0)), (nat_lit 629, Int.negSucc (nat_lit 0)), (nat_lit 641, Int.negSucc (nat_lit 1)), (nat_lit 642, Int.negSucc (nat_lit 1)), (nat_lit 643, Int.negSucc (nat_lit 0)), (nat_lit 785, Int.negSucc (nat_lit 0)), (nat_lit 786, Int.negSucc (nat_lit 1)), (nat_lit 787, Int.negSucc (nat_lit 0)), (nat_lit 798, Int.negSucc (nat_lit 0)), (nat_lit 799, Int.negSucc (nat_lit 0))]
theorem det00Term1Row05_decode : SparsePolynomial.decodeCubic 12 det00Term1Row05 = SparsePolynomial.monoTimes [5] (-1 : Int) det00Pair1 := by decide +kernel
theorem eval_det00Term1Row05 (g : Fin 12 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 12) det00Term1Row05 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [5]*SparsePolynomial.eval (gapValues g) det00Pair1 := by
  rw [← SparsePolynomial.eval_decodeCubic, det00Term1Row05_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det00Term1Row06 : CoefficientMerge.Poly := [(nat_lit 174, Int.negSucc (nat_lit 0)), (nat_lit 186, Int.negSucc (nat_lit 0)), (nat_lit 198, Int.negSucc (nat_lit 0)), (nat_lit 210, Int.negSucc (nat_lit 0)), (nat_lit 222, Int.negSucc (nat_lit 0)), (nat_lit 318, Int.negSucc (nat_lit 0)), (nat_lit 330, Int.negSucc (nat_lit 1)), (nat_lit 342, Int.negSucc (nat_lit 1)), (nat_lit 354, Int.negSucc (nat_lit 1)), (nat_lit 366, Int.negSucc (nat_lit 1)), (nat_lit 367, Int.negSucc (nat_lit 0)), (nat_lit 474, Int.negSucc (nat_lit 0)), (nat_lit 486, Int.negSucc (nat_lit 1)), (nat_lit 498, Int.negSucc (nat_lit 1)), (nat_lit 510, Int.negSucc (nat_lit 1)), (nat_lit 511, Int.negSucc (nat_lit 0)), (nat_lit 630, Int.negSucc (nat_lit 0)), (nat_lit 642, Int.negSucc (nat_lit 1)), (nat_lit 654, Int.negSucc (nat_lit 1)), (nat_lit 655, Int.negSucc (nat_lit 0)), (nat_lit 786, Int.negSucc (nat_lit 0)), (nat_lit 798, Int.negSucc (nat_lit 1)), (nat_lit 799, Int.negSucc (nat_lit 0)), (nat_lit 942, Int.negSucc (nat_lit 0)), (nat_lit 943, Int.negSucc (nat_lit 0))]
theorem det00Term1Row06_decode : SparsePolynomial.decodeCubic 12 det00Term1Row06 = SparsePolynomial.monoTimes [6] (-1 : Int) det00Pair1 := by decide +kernel
theorem eval_det00Term1Row06 (g : Fin 12 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 12) det00Term1Row06 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [6]*SparsePolynomial.eval (gapValues g) det00Pair1 := by
  rw [← SparsePolynomial.eval_decodeCubic, det00Term1Row06_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det00Term1Row07 : CoefficientMerge.Poly := [(nat_lit 175, Int.negSucc (nat_lit 0)), (nat_lit 187, Int.negSucc (nat_lit 0)), (nat_lit 199, Int.negSucc (nat_lit 0)), (nat_lit 211, Int.negSucc (nat_lit 0)), (nat_lit 223, Int.negSucc (nat_lit 0)), (nat_lit 319, Int.negSucc (nat_lit 0)), (nat_lit 331, Int.negSucc (nat_lit 1)), (nat_lit 343, Int.negSucc (nat_lit 1)), (nat_lit 355, Int.negSucc (nat_lit 1)), (nat_lit 367, Int.negSucc (nat_lit 1)), (nat_lit 379, Int.negSucc (nat_lit 0)), (nat_lit 475, Int.negSucc (nat_lit 0)), (nat_lit 487, Int.negSucc (nat_lit 1)), (nat_lit 499, Int.negSucc (nat_lit 1)), (nat_lit 511, Int.negSucc (nat_lit 1)), (nat_lit 523, Int.negSucc (nat_lit 0)), (nat_lit 631, Int.negSucc (nat_lit 0)), (nat_lit 643, Int.negSucc (nat_lit 1)), (nat_lit 655, Int.negSucc (nat_lit 1)), (nat_lit 667, Int.negSucc (nat_lit 0)), (nat_lit 787, Int.negSucc (nat_lit 0)), (nat_lit 799, Int.negSucc (nat_lit 1)), (nat_lit 811, Int.negSucc (nat_lit 0)), (nat_lit 943, Int.negSucc (nat_lit 0)), (nat_lit 955, Int.negSucc (nat_lit 0))]
theorem det00Term1Row07_decode : SparsePolynomial.decodeCubic 12 det00Term1Row07 = SparsePolynomial.monoTimes [7] (-1 : Int) det00Pair1 := by decide +kernel
theorem eval_det00Term1Row07 (g : Fin 12 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 12) det00Term1Row07 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [7]*SparsePolynomial.eval (gapValues g) det00Pair1 := by
  rw [← SparsePolynomial.eval_decodeCubic, det00Term1Row07_decode, SparsePolynomial.eval_monoTimes]
  norm_num

end APPT.Finite12
