import APPT.Finite12Sparse.Det00Pair2
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
open scoped BigOperators
namespace APPT.Finite12
open SparsePolynomial

def det00Term2Row00 : CoefficientMerge.Poly := [(nat_lit 14, Int.negSucc (nat_lit 0)), (nat_lit 15, Int.negSucc (nat_lit 0)), (nat_lit 16, Int.negSucc (nat_lit 0)), (nat_lit 17, Int.negSucc (nat_lit 0)), (nat_lit 18, Int.negSucc (nat_lit 0)), (nat_lit 158, Int.negSucc (nat_lit 0)), (nat_lit 159, Int.negSucc (nat_lit 0)), (nat_lit 160, Int.negSucc (nat_lit 0)), (nat_lit 161, Int.negSucc (nat_lit 0)), (nat_lit 162, Int.negSucc (nat_lit 0)), (nat_lit 170, Int.negSucc (nat_lit 0)), (nat_lit 171, Int.negSucc (nat_lit 1)), (nat_lit 172, Int.negSucc (nat_lit 1)), (nat_lit 173, Int.negSucc (nat_lit 1)), (nat_lit 174, Int.negSucc (nat_lit 1)), (nat_lit 175, Int.negSucc (nat_lit 0)), (nat_lit 176, Int.negSucc (nat_lit 0)), (nat_lit 177, Int.negSucc (nat_lit 0)), (nat_lit 183, Int.negSucc (nat_lit 0)), (nat_lit 184, Int.negSucc (nat_lit 1)), (nat_lit 185, Int.negSucc (nat_lit 1)), (nat_lit 186, Int.negSucc (nat_lit 1)), (nat_lit 187, Int.negSucc (nat_lit 0)), (nat_lit 188, Int.negSucc (nat_lit 0)), (nat_lit 189, Int.negSucc (nat_lit 0)), (nat_lit 196, Int.negSucc (nat_lit 0)), (nat_lit 197, Int.negSucc (nat_lit 1)), (nat_lit 198, Int.negSucc (nat_lit 1)), (nat_lit 199, Int.negSucc (nat_lit 0)), (nat_lit 200, Int.negSucc (nat_lit 0)), (nat_lit 201, Int.negSucc (nat_lit 0)), (nat_lit 209, Int.negSucc (nat_lit 0)), (nat_lit 210, Int.negSucc (nat_lit 1)), (nat_lit 211, Int.negSucc (nat_lit 0)), (nat_lit 212, Int.negSucc (nat_lit 0)), (nat_lit 213, Int.negSucc (nat_lit 0)), (nat_lit 222, Int.negSucc (nat_lit 0)), (nat_lit 223, Int.negSucc (nat_lit 0)), (nat_lit 224, Int.negSucc (nat_lit 0)), (nat_lit 225, Int.negSucc (nat_lit 0))]
theorem det00Term2Row00_decode : SparsePolynomial.decodeCubic 12 det00Term2Row00 = SparsePolynomial.monoTimes [1] (-1 : Int) det00Pair2 := by decide +kernel
theorem eval_det00Term2Row00 (g : Fin 12 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 12) det00Term2Row00 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [1]*SparsePolynomial.eval (gapValues g) det00Pair2 := by
  rw [← SparsePolynomial.eval_decodeCubic, det00Term2Row00_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det00Term2Row01 : CoefficientMerge.Poly := [(nat_lit 26, Int.negSucc (nat_lit 0)), (nat_lit 27, Int.negSucc (nat_lit 0)), (nat_lit 28, Int.negSucc (nat_lit 0)), (nat_lit 29, Int.negSucc (nat_lit 0)), (nat_lit 30, Int.negSucc (nat_lit 0)), (nat_lit 170, Int.negSucc (nat_lit 0)), (nat_lit 171, Int.negSucc (nat_lit 0)), (nat_lit 172, Int.negSucc (nat_lit 0)), (nat_lit 173, Int.negSucc (nat_lit 0)), (nat_lit 174, Int.negSucc (nat_lit 0)), (nat_lit 314, Int.negSucc (nat_lit 0)), (nat_lit 315, Int.negSucc (nat_lit 1)), (nat_lit 316, Int.negSucc (nat_lit 1)), (nat_lit 317, Int.negSucc (nat_lit 1)), (nat_lit 318, Int.negSucc (nat_lit 1)), (nat_lit 319, Int.negSucc (nat_lit 0)), (nat_lit 320, Int.negSucc (nat_lit 0)), (nat_lit 321, Int.negSucc (nat_lit 0)), (nat_lit 327, Int.negSucc (nat_lit 0)), (nat_lit 328, Int.negSucc (nat_lit 1)), (nat_lit 329, Int.negSucc (nat_lit 1)), (nat_lit 330, Int.negSucc (nat_lit 1)), (nat_lit 331, Int.negSucc (nat_lit 0)), (nat_lit 332, Int.negSucc (nat_lit 0)), (nat_lit 333, Int.negSucc (nat_lit 0)), (nat_lit 340, Int.negSucc (nat_lit 0)), (nat_lit 341, Int.negSucc (nat_lit 1)), (nat_lit 342, Int.negSucc (nat_lit 1)), (nat_lit 343, Int.negSucc (nat_lit 0)), (nat_lit 344, Int.negSucc (nat_lit 0)), (nat_lit 345, Int.negSucc (nat_lit 0)), (nat_lit 353, Int.negSucc (nat_lit 0)), (nat_lit 354, Int.negSucc (nat_lit 1)), (nat_lit 355, Int.negSucc (nat_lit 0)), (nat_lit 356, Int.negSucc (nat_lit 0)), (nat_lit 357, Int.negSucc (nat_lit 0)), (nat_lit 366, Int.negSucc (nat_lit 0)), (nat_lit 367, Int.negSucc (nat_lit 0)), (nat_lit 368, Int.negSucc (nat_lit 0)), (nat_lit 369, Int.negSucc (nat_lit 0))]
theorem det00Term2Row01_decode : SparsePolynomial.decodeCubic 12 det00Term2Row01 = SparsePolynomial.monoTimes [2] (-1 : Int) det00Pair2 := by decide +kernel
theorem eval_det00Term2Row01 (g : Fin 12 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 12) det00Term2Row01 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [2]*SparsePolynomial.eval (gapValues g) det00Pair2 := by
  rw [← SparsePolynomial.eval_decodeCubic, det00Term2Row01_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det00Term2Row02 : CoefficientMerge.Poly := [(nat_lit 27, Int.negSucc (nat_lit 0)), (nat_lit 39, Int.negSucc (nat_lit 0)), (nat_lit 40, Int.negSucc (nat_lit 0)), (nat_lit 41, Int.negSucc (nat_lit 0)), (nat_lit 42, Int.negSucc (nat_lit 0)), (nat_lit 171, Int.negSucc (nat_lit 0)), (nat_lit 183, Int.negSucc (nat_lit 0)), (nat_lit 184, Int.negSucc (nat_lit 0)), (nat_lit 185, Int.negSucc (nat_lit 0)), (nat_lit 186, Int.negSucc (nat_lit 0)), (nat_lit 315, Int.negSucc (nat_lit 0)), (nat_lit 327, Int.negSucc (nat_lit 1)), (nat_lit 328, Int.negSucc (nat_lit 1)), (nat_lit 329, Int.negSucc (nat_lit 1)), (nat_lit 330, Int.negSucc (nat_lit 1)), (nat_lit 331, Int.negSucc (nat_lit 0)), (nat_lit 332, Int.negSucc (nat_lit 0)), (nat_lit 333, Int.negSucc (nat_lit 0)), (nat_lit 471, Int.negSucc (nat_lit 0)), (nat_lit 472, Int.negSucc (nat_lit 1)), (nat_lit 473, Int.negSucc (nat_lit 1)), (nat_lit 474, Int.negSucc (nat_lit 1)), (nat_lit 475, Int.negSucc (nat_lit 0)), (nat_lit 476, Int.negSucc (nat_lit 0)), (nat_lit 477, Int.negSucc (nat_lit 0)), (nat_lit 484, Int.negSucc (nat_lit 0)), (nat_lit 485, Int.negSucc (nat_lit 1)), (nat_lit 486, Int.negSucc (nat_lit 1)), (nat_lit 487, Int.negSucc (nat_lit 0)), (nat_lit 488, Int.negSucc (nat_lit 0)), (nat_lit 489, Int.negSucc (nat_lit 0)), (nat_lit 497, Int.negSucc (nat_lit 0)), (nat_lit 498, Int.negSucc (nat_lit 1)), (nat_lit 499, Int.negSucc (nat_lit 0)), (nat_lit 500, Int.negSucc (nat_lit 0)), (nat_lit 501, Int.negSucc (nat_lit 0)), (nat_lit 510, Int.negSucc (nat_lit 0)), (nat_lit 511, Int.negSucc (nat_lit 0)), (nat_lit 512, Int.negSucc (nat_lit 0)), (nat_lit 513, Int.negSucc (nat_lit 0))]
theorem det00Term2Row02_decode : SparsePolynomial.decodeCubic 12 det00Term2Row02 = SparsePolynomial.monoTimes [3] (-1 : Int) det00Pair2 := by decide +kernel
theorem eval_det00Term2Row02 (g : Fin 12 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 12) det00Term2Row02 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [3]*SparsePolynomial.eval (gapValues g) det00Pair2 := by
  rw [← SparsePolynomial.eval_decodeCubic, det00Term2Row02_decode, SparsePolynomial.eval_monoTimes]
  norm_num
def det00Term2Row03 : CoefficientMerge.Poly := [(nat_lit 28, Int.negSucc (nat_lit 0)), (nat_lit 40, Int.negSucc (nat_lit 0)), (nat_lit 52, Int.negSucc (nat_lit 0)), (nat_lit 53, Int.negSucc (nat_lit 0)), (nat_lit 54, Int.negSucc (nat_lit 0)), (nat_lit 172, Int.negSucc (nat_lit 0)), (nat_lit 184, Int.negSucc (nat_lit 0)), (nat_lit 196, Int.negSucc (nat_lit 0)), (nat_lit 197, Int.negSucc (nat_lit 0)), (nat_lit 198, Int.negSucc (nat_lit 0)), (nat_lit 316, Int.negSucc (nat_lit 0)), (nat_lit 328, Int.negSucc (nat_lit 1)), (nat_lit 340, Int.negSucc (nat_lit 1)), (nat_lit 341, Int.negSucc (nat_lit 1)), (nat_lit 342, Int.negSucc (nat_lit 1)), (nat_lit 343, Int.negSucc (nat_lit 0)), (nat_lit 344, Int.negSucc (nat_lit 0)), (nat_lit 345, Int.negSucc (nat_lit 0)), (nat_lit 472, Int.negSucc (nat_lit 0)), (nat_lit 484, Int.negSucc (nat_lit 1)), (nat_lit 485, Int.negSucc (nat_lit 1)), (nat_lit 486, Int.negSucc (nat_lit 1)), (nat_lit 487, Int.negSucc (nat_lit 0)), (nat_lit 488, Int.negSucc (nat_lit 0)), (nat_lit 489, Int.negSucc (nat_lit 0)), (nat_lit 628, Int.negSucc (nat_lit 0)), (nat_lit 629, Int.negSucc (nat_lit 1)), (nat_lit 630, Int.negSucc (nat_lit 1)), (nat_lit 631, Int.negSucc (nat_lit 0)), (nat_lit 632, Int.negSucc (nat_lit 0)), (nat_lit 633, Int.negSucc (nat_lit 0)), (nat_lit 641, Int.negSucc (nat_lit 0)), (nat_lit 642, Int.negSucc (nat_lit 1)), (nat_lit 643, Int.negSucc (nat_lit 0)), (nat_lit 644, Int.negSucc (nat_lit 0)), (nat_lit 645, Int.negSucc (nat_lit 0)), (nat_lit 654, Int.negSucc (nat_lit 0)), (nat_lit 655, Int.negSucc (nat_lit 0)), (nat_lit 656, Int.negSucc (nat_lit 0)), (nat_lit 657, Int.negSucc (nat_lit 0))]
theorem det00Term2Row03_decode : SparsePolynomial.decodeCubic 12 det00Term2Row03 = SparsePolynomial.monoTimes [4] (-1 : Int) det00Pair2 := by decide +kernel
theorem eval_det00Term2Row03 (g : Fin 12 → ℝ) : CoefficientMerge.eval (SparsePolynomial.cubeValue (gapValues g) 12) det00Term2Row03 = (-1 : ℝ)*SparsePolynomial.mon (gapValues g) [4]*SparsePolynomial.eval (gapValues g) det00Pair2 := by
  rw [← SparsePolynomial.eval_decodeCubic, det00Term2Row03_decode, SparsePolynomial.eval_monoTimes]
  norm_num

end APPT.Finite12
