import GaussianFourProgress

#check GaussianMeasureBridge.FractionalPartition.norm_label_le_one
#print axioms GaussianMeasureBridge.FractionalPartition.norm_label_le_one
#check GaussianMeasureBridge.FractionalPartition.integrable_label
#print axioms GaussianMeasureBridge.FractionalPartition.integrable_label
#check GaussianMeasureBridge.FractionalPartition.integrable_weighted_id
#print axioms GaussianMeasureBridge.FractionalPartition.integrable_weighted_id
#check GaussianMeasureBridge.FractionalPartition.mass_nonneg
#print axioms GaussianMeasureBridge.FractionalPartition.mass_nonneg
#check GaussianMeasureBridge.FractionalPartition.sum_mass
#print axioms GaussianMeasureBridge.FractionalPartition.sum_mass
#check GaussianMeasureBridge.FractionalPartition.sum_moment
#print axioms GaussianMeasureBridge.FractionalPartition.sum_moment
#check GaussianMeasureBridge.FractionalPartition.inner_moment
#print axioms GaussianMeasureBridge.FractionalPartition.inner_moment
#check GaussianMeasureBridge.le_scoreMax
#print axioms GaussianMeasureBridge.le_scoreMax
#check GaussianMeasureBridge.integrable_score
#print axioms GaussianMeasureBridge.integrable_score
#check GaussianMeasureBridge.integrable_scoreMax
#print axioms GaussianMeasureBridge.integrable_scoreMax
#check GaussianMeasureBridge.continuous_scoreMax
#print axioms GaussianMeasureBridge.continuous_scoreMax
#check GaussianMeasureBridge.FractionalPartition.integrable_weighted_score
#print axioms GaussianMeasureBridge.FractionalPartition.integrable_weighted_score
#check GaussianMeasureBridge.FractionalPartition.integral_weighted_score
#print axioms GaussianMeasureBridge.FractionalPartition.integral_weighted_score
#check GaussianMeasureBridge.FractionalPartition.price_dual
#print axioms GaussianMeasureBridge.FractionalPartition.price_dual
#check GaussianMeasureBridge.integral_score
#print axioms GaussianMeasureBridge.integral_score
#check GaussianMeasureBridge.scoreMax_le_add_norm
#print axioms GaussianMeasureBridge.scoreMax_le_add_norm
#check GaussianMeasureBridge.scoreMax_abs_sub_le
#print axioms GaussianMeasureBridge.scoreMax_abs_sub_le
#check GaussianMeasureBridge.expectedScore_lipschitz
#print axioms GaussianMeasureBridge.expectedScore_lipschitz
#check GaussianMeasureBridge.continuous_priceObjective
#print axioms GaussianMeasureBridge.continuous_priceObjective
#check GaussianMeasureBridge.scoreMax_sub_const
#print axioms GaussianMeasureBridge.scoreMax_sub_const
#check GaussianMeasureBridge.priceObjective_sub_const
#print axioms GaussianMeasureBridge.priceObjective_sub_const
#check GaussianMeasureBridge.expectedScore_nonneg_of_zero
#print axioms GaussianMeasureBridge.expectedScore_nonneg_of_zero
#check GaussianMeasureBridge.weighted_price_le_objective
#print axioms GaussianMeasureBridge.weighted_price_le_objective
#check GaussianMeasureBridge.exists_price_minimizer
#print axioms GaussianMeasureBridge.exists_price_minimizer
#check GaussianMeasureBridge.gaussian_hyperplane_null
#print axioms GaussianMeasureBridge.gaussian_hyperplane_null
#check GaussianMeasureBridge.ae_scores_pairwise_ne
#print axioms GaussianMeasureBridge.ae_scores_pairwise_ne
#check GaussianMeasureBridge.measurableSet_winningCell
#print axioms GaussianMeasureBridge.measurableSet_winningCell
#check GaussianMeasureBridge.ae_unique_winner
#print axioms GaussianMeasureBridge.ae_unique_winner
#check GaussianMeasureBridge.gaussian_open_pos
#print axioms GaussianMeasureBridge.gaussian_open_pos
#check GaussianMeasureBridge.coordinateShift_zero
#print axioms GaussianMeasureBridge.coordinateShift_zero
#check GaussianMeasureBridge.coordinateShift_dist_le
#print axioms GaussianMeasureBridge.coordinateShift_dist_le
#check GaussianMeasureBridge.coordinateScore_lipschitz
#print axioms GaussianMeasureBridge.coordinateScore_lipschitz
#check GaussianMeasureBridge.scoreMax_eq_winning_score
#print axioms GaussianMeasureBridge.scoreMax_eq_winning_score
#check GaussianMeasureBridge.winningCell_disjoint
#print axioms GaussianMeasureBridge.winningCell_disjoint
#check GaussianMeasureBridge.coordinateScore_hasDerivAt
#print axioms GaussianMeasureBridge.coordinateScore_hasDerivAt
#check GaussianMeasureBridge.expectedScore_coordinate_derivative
#print axioms GaussianMeasureBridge.expectedScore_coordinate_derivative
#check GaussianMeasureBridge.weighted_price_coordinate
#print axioms GaussianMeasureBridge.weighted_price_coordinate
#check GaussianMeasureBridge.priceObjective_coordinate_derivative
#print axioms GaussianMeasureBridge.priceObjective_coordinate_derivative
#check GaussianMeasureBridge.exists_balancing_prices
#print axioms GaussianMeasureBridge.exists_balancing_prices
#check GaussianMeasureBridge.winningPartition_mass
#print axioms GaussianMeasureBridge.winningPartition_mass
#check GaussianMeasureBridge.winningPartition_dual_attainment
#print axioms GaussianMeasureBridge.winningPartition_dual_attainment
#check GaussianMeasureBridge.balanced_price_is_minimizer
#print axioms GaussianMeasureBridge.balanced_price_is_minimizer
#check GaussianMeasureBridge.scoreMid_le
#print axioms GaussianMeasureBridge.scoreMid_le
#check GaussianMeasureBridge.weighted_priceMid
#print axioms GaussianMeasureBridge.weighted_priceMid
#check GaussianMeasureBridge.minimizers_jensen_gap_zero
#print axioms GaussianMeasureBridge.minimizers_jensen_gap_zero
#check GaussianMeasureBridge.common_maximizer_of_jensen_zero
#print axioms GaussianMeasureBridge.common_maximizer_of_jensen_zero
#check GaussianMeasureBridge.minimizers_score_difference_constant
#print axioms GaussianMeasureBridge.minimizers_score_difference_constant
#check GaussianMeasureBridge.balancing_prices_unique_mod_const
#print axioms GaussianMeasureBridge.balancing_prices_unique_mod_const
#check GaussianMeasureBridge.actual_gaussian_primal_dual
#print axioms GaussianMeasureBridge.actual_gaussian_primal_dual
#check GaussianMeasureBridge.fractional_dual_equality_ae_winning
#print axioms GaussianMeasureBridge.fractional_dual_equality_ae_winning
#check GaussianFourGlobal.densityCap_pos
#print axioms GaussianFourGlobal.densityCap_pos
#check GaussianFourGlobal.densityCap_eq
#print axioms GaussianFourGlobal.densityCap_eq
#check GaussianFourGlobal.gaussianPDF_le_densityCap
#print axioms GaussianFourGlobal.gaussianPDF_le_densityCap
#check GaussianFourGlobal.tent_nonneg
#print axioms GaussianFourGlobal.tent_nonneg
#check GaussianFourGlobal.tent_le
#print axioms GaussianFourGlobal.tent_le
#check GaussianFourGlobal.continuous_tent
#print axioms GaussianFourGlobal.continuous_tent
#check GaussianFourGlobal.tent_eq_zero_outside
#print axioms GaussianFourGlobal.tent_eq_zero_outside
#check GaussianFourGlobal.integrable_tent
#print axioms GaussianFourGlobal.integrable_tent
#check GaussianFourGlobal.integral_tent
#print axioms GaussianFourGlobal.integral_tent
#check GaussianFourGlobal.gaussianReal_tent_bound
#print axioms GaussianFourGlobal.gaussianReal_tent_bound
#check GaussianFourGlobal.unit_inner_law
#print axioms GaussianFourGlobal.unit_inner_law
#check GaussianFourGlobal.gaussian_inner_tent_bound
#print axioms GaussianFourGlobal.gaussian_inner_tent_bound
#check GaussianFourGlobal.integrable_inner_tent
#print axioms GaussianFourGlobal.integrable_inner_tent
#check GaussianFourGlobal.two_label_tent
#print axioms GaussianFourGlobal.two_label_tent
#check GaussianFourGlobal.pair_label_sum_le_one
#print axioms GaussianFourGlobal.pair_label_sum_le_one
#check GaussianFourGlobal.fractional_pair_separation
#print axioms GaussianFourGlobal.fractional_pair_separation
#check GaussianFourGlobal.fractional_equal_mass_pair_separation
#print axioms GaussianFourGlobal.fractional_equal_mass_pair_separation
#check GaussianFourGlobal.separationConstant_pos
#print axioms GaussianFourGlobal.separationConstant_pos
#check GaussianFourGlobal.separationConstant_eq
#print axioms GaussianFourGlobal.separationConstant_eq
#check GaussianFourGlobal.balanced_winning_moment_separation
#print axioms GaussianFourGlobal.balanced_winning_moment_separation
#check GaussianFourGlobal.balanced_winning_moment_norm_separation
#print axioms GaussianFourGlobal.balanced_winning_moment_norm_separation
#check GaussianFourGlobal.eventually_winningCell
#print axioms GaussianFourGlobal.eventually_winningCell
#check GaussianFourGlobal.eventually_winning_memberships
#print axioms GaussianFourGlobal.eventually_winning_memberships
#check GaussianFourGlobal.ae_tendsto_winning_indicator
#print axioms GaussianFourGlobal.ae_tendsto_winning_indicator
#check GaussianFourGlobal.tendsto_winning_setIntegral
#print axioms GaussianFourGlobal.tendsto_winning_setIntegral
#check GaussianFourGlobal.tendsto_winning_mass
#print axioms GaussianFourGlobal.tendsto_winning_mass
#check GaussianFourGlobal.winningPartition_moment_eq_setIntegral
#print axioms GaussianFourGlobal.winningPartition_moment_eq_setIntegral
#check GaussianFourGlobal.tendsto_winning_moment
#print axioms GaussianFourGlobal.tendsto_winning_moment
#check GaussianFourGlobal.balanced_winning_limit
#print axioms GaussianFourGlobal.balanced_winning_limit
#check GaussianFourGlobal.tendsto_moment_of_residual
#print axioms GaussianFourGlobal.tendsto_moment_of_residual
#check GaussianFourGlobal.residual_limit_pair_separation
#print axioms GaussianFourGlobal.residual_limit_pair_separation
#check GaussianFourGlobal.residual_limit_injective
#print axioms GaussianFourGlobal.residual_limit_injective
#check GaussianFourGlobal.residual_limit_multiplier_pos
#print axioms GaussianFourGlobal.residual_limit_multiplier_pos
#check GaussianFourGlobal.balanced_residual_limit
#print axioms GaussianFourGlobal.balanced_residual_limit
#check GaussianFourGlobal.winningCell_pos_scale
#print axioms GaussianFourGlobal.winningCell_pos_scale
#check GaussianFourGlobal.balanced_limit_self_moment
#print axioms GaussianFourGlobal.balanced_limit_self_moment
#check GaussianFourGlobal.uniformPartition_mass
#print axioms GaussianFourGlobal.uniformPartition_mass
#check GaussianFourGlobal.uniformPartition_moment
#print axioms GaussianFourGlobal.uniformPartition_moment
#check GaussianFourGlobal.balancedValue_eq_minimizer
#print axioms GaussianFourGlobal.balancedValue_eq_minimizer
#check GaussianFourGlobal.balancedValue_attained
#print axioms GaussianFourGlobal.balancedValue_attained
#check GaussianFourGlobal.balancedValue_le_price
#print axioms GaussianFourGlobal.balancedValue_le_price
#check GaussianFourGlobal.fractional_value_le_balancedValue
#print axioms GaussianFourGlobal.fractional_value_le_balancedValue
#check GaussianFourGlobal.balancedValue_nonneg
#print axioms GaussianFourGlobal.balancedValue_nonneg
#check GaussianFourGlobal.gaussianRadius_nonneg
#print axioms GaussianFourGlobal.gaussianRadius_nonneg
#check GaussianFourGlobal.scoreMax_score_le
#print axioms GaussianFourGlobal.scoreMax_score_le
#check GaussianFourGlobal.expectedScore_score_le
#print axioms GaussianFourGlobal.expectedScore_score_le
#check GaussianFourGlobal.balancedValue_score_le
#print axioms GaussianFourGlobal.balancedValue_score_le
#check GaussianFourGlobal.balancedValue_abs_sub_le
#print axioms GaussianFourGlobal.balancedValue_abs_sub_le
#check GaussianFourGlobal.balancedValue_lipschitz
#print axioms GaussianFourGlobal.balancedValue_lipschitz
#check GaussianFourGlobal.continuous_balancedValue
#print axioms GaussianFourGlobal.continuous_balancedValue
#check GaussianFourGlobal.expectedScore_zero_zero
#print axioms GaussianFourGlobal.expectedScore_zero_zero
#check GaussianFourGlobal.balanced_price_bound
#print axioms GaussianFourGlobal.balanced_price_bound
#check GaussianFourGlobal.scoreMax_scale_nonneg
#print axioms GaussianFourGlobal.scoreMax_scale_nonneg
#check GaussianFourGlobal.priceObjective_scale_nonneg
#print axioms GaussianFourGlobal.priceObjective_scale_nonneg
#check GaussianFourGlobal.balancedValue_zero
#print axioms GaussianFourGlobal.balancedValue_zero
#check GaussianFourGlobal.balancedValue_pos_scale
#print axioms GaussianFourGlobal.balancedValue_pos_scale
#check GaussianFourGlobal.balancedValue_scale_nonneg
#print axioms GaussianFourGlobal.balancedValue_scale_nonneg
#check GaussianFourGlobal.momentEnergy_nonneg
#print axioms GaussianFourGlobal.momentEnergy_nonneg
#check GaussianFourGlobal.uniformPartition_energy
#print axioms GaussianFourGlobal.uniformPartition_energy
#check GaussianFourGlobal.self_partitionValue
#print axioms GaussianFourGlobal.self_partitionValue
#check GaussianFourGlobal.energy_le_balancedValue
#print axioms GaussianFourGlobal.energy_le_balancedValue
#check GaussianFourGlobal.sum_normalizedMoments
#print axioms GaussianFourGlobal.sum_normalizedMoments
#check GaussianFourGlobal.normalizedMoments_energy_one
#print axioms GaussianFourGlobal.normalizedMoments_energy_one
#check GaussianFourGlobal.normalized_partitionValue
#print axioms GaussianFourGlobal.normalized_partitionValue
#check GaussianFourGlobal.sqrt_energy_le_normalized_value
#print axioms GaussianFourGlobal.sqrt_energy_le_normalized_value
#check GaussianFourGlobal.winning_labels_of_energy_value_equality
#print axioms GaussianFourGlobal.winning_labels_of_energy_value_equality
#check GaussianFourGlobal.SetPartition.toFractional_mass
#print axioms GaussianFourGlobal.SetPartition.toFractional_mass
#check GaussianFourGlobal.SetPartition.toFractional_moment
#print axioms GaussianFourGlobal.SetPartition.toFractional_moment
#check GaussianFourGlobal.SetPartition.sum_set_moment
#print axioms GaussianFourGlobal.SetPartition.sum_set_moment
#check GaussianFourGlobal.SetPartition.moment_eq_of_ae_cells
#print axioms GaussianFourGlobal.SetPartition.moment_eq_of_ae_cells
#check GaussianFourGlobal.SetPartition.mass_quarter
#print axioms GaussianFourGlobal.SetPartition.mass_quarter
#check GaussianFourGlobal.SetPartition.energy_le_value
#print axioms GaussianFourGlobal.SetPartition.energy_le_value
#check GaussianFourGlobal.SetPartition.normalized_reduction
#print axioms GaussianFourGlobal.SetPartition.normalized_reduction
#check GaussianFourGlobal.scoreMap_apply
#print axioms GaussianFourGlobal.scoreMap_apply
#check GaussianFourGlobal.scoreMap_inner
#print axioms GaussianFourGlobal.scoreMap_inner
#check GaussianFourGlobal.gaussian_inner_law
#print axioms GaussianFourGlobal.gaussian_inner_law
#check GaussianFourGlobal.norm_sum_smul_sq_of_gram_eq
#print axioms GaussianFourGlobal.norm_sum_smul_sq_of_gram_eq
#check GaussianFourGlobal.scoreLaw_eq_of_gram_eq
#print axioms GaussianFourGlobal.scoreLaw_eq_of_gram_eq
#check GaussianFourGlobal.continuous_coordinateMax
#print axioms GaussianFourGlobal.continuous_coordinateMax
#check GaussianFourGlobal.expectedScore_eq_scoreLaw_integral
#print axioms GaussianFourGlobal.expectedScore_eq_scoreLaw_integral
#check GaussianFourGlobal.expectedScore_eq_of_gram_eq
#print axioms GaussianFourGlobal.expectedScore_eq_of_gram_eq
#check GaussianFourGlobal.priceObjective_eq_of_gram_eq
#print axioms GaussianFourGlobal.priceObjective_eq_of_gram_eq
#check GaussianFourGlobal.balancedValue_eq_of_gram_eq
#print axioms GaussianFourGlobal.balancedValue_eq_of_gram_eq
#check GaussianFourGlobal.balancedValue_isometric_embedding
#print axioms GaussianFourGlobal.balancedValue_isometric_embedding
#check GaussianFourGlobal.uniform_not_ae_indicator
#print axioms GaussianFourGlobal.uniform_not_ae_indicator
