#!/usr/bin/env python3
"""Independent exact fractional certificate replay for k=4, 11<=n<=64.

No numerical optimizer or SymPy. Every feasible cycle-count quadruple
is enumerated. JSON is frozen and not generated by this checker.
"""
from fractions import Fraction as F
from itertools import product
from math import comb,factorial,lcm
from json import loads
from pathlib import Path

def C(n,j):return comb(n,j) if 0<=j<=n else 0

def orb(n,x,y,z,w):
 N=C(n,4)
 B1=x*C(n-1,3)+(n-x)*C(n-2,2)
 v22=C(x,2)+y
 v21=x*(n-x)+(n-x-2*y)
 v20=C(n,2)-v21-v22
 B2=v20+(n-3)*v21+C(n-2,2)*v22
 v33=C(x,3)+x*y+z
 v32=C(x,2)*(n-x)+x*(n-x-2*y)+y*(n-2-x)+(n-x-2*y-3*z)
 B3=v32+(n-3)*v33
 B4=C(x,4)+C(x,2)*y+C(y,2)+x*z+w
 B=[N,B1,B2,B3,B4]
 Fv=[sum((-1)**(j-i)*C(j,i)*B[j] for j in range(i,5))
     for i in range(5)]
 assert min(Fv)>=0 and sum(Fv)==N
 return Fv

def types(n):
 for x in range(n+1):
  for y in range((n-x)//2+1):
   for z in range((n-x-2*y)//3+1):
    for w in range((n-x-2*y-3*z)//4+1):
     r=n-x-2*y-3*z-4*w
     if r==0 or r>=5:yield (x,y,z,w,r)

def class_size(n,T):
 x,y,z,w,r=T
 den=factorial(x)*2**y*factorial(y)*3**z*factorial(z)*4**w*factorial(w)
 if r:den*=r
 assert factorial(n)%den==0
 return factorial(n)//den

def verify(R):
 n=R['n']
 P=[(tuple(v['type']),F(v['weight'])) for v in R['P']]
 Q=[(tuple(v['type']),F(v['weight'])) for v in R['Q']]
 assert len(P)==len(Q) and len(P) in (2,3) and P[0][0]==(n,0,0,0,0)
 assert len({t for t,v in P+Q})==len(P)+len(Q)
 assert all(t[0]+2*t[1]+3*t[2]+4*t[3]+t[4]==n for t,v in P+Q)
 assert all(v>0 for t,v in P+Q)
 assert sum(v for t,v in P)==sum(v for t,v in Q)==1
 for j in range(5):
  assert sum(v*orb(n,*t[:4])[j] for t,v in P)==sum(
              v*orb(n,*t[:4])[j] for t,v in Q),(n,j)
 lam=[F(v) for v in R['dual']]
 hi,lo,C0=F(R['upper']),F(R['lower']),F(R['C'])
 assert len(lam)==4 and hi-lo==C0==P[0][1] and 0<C0<1
 D=lcm(*(v.denominator for v in lam+[hi,lo]))
 numer=[int(D*z) for z in lam]
 mn,mx=int(D*lo),int(D*hi)
 ptypes={t for t,v in P}
 qtypes={t for t,v in Q}
 for t,v in P+Q:
  vals=orb(n,*t[:4])
  h=(D if t[0]==n else 0)-sum(numer[j]*vals[j] for j in range(4))
  assert h==(mx if t in ptypes else mn),(n,'touch',t,h,mn,mx)
 count=0
 for t in types(n):
  vals=orb(n,*t[:4])
  h=(D if t[0]==n else 0)-sum(numer[j]*vals[j] for j in range(4))
  assert mn<=h<=mx,(n,t,h,mn,mx)
  count+=1
 dens=max(v/class_size(n,t) for t,v in Q)
 delta=F(1,2*factorial(n)*dens)
 assert delta>0 and all(F(1,factorial(n))-delta*v/class_size(n,t)>=0 for t,v in Q)
 return count,C0

data=loads((Path(__file__).resolve().parents[1]/'certificates'/'four_subset_n8_64.json').read_text())
records=data['degrees']
assert [r['n'] for r in records]==list(range(8,65))
N=0
for r in records:
 count,val=verify(r)
 N+=count
 if r['n']<=18 or r['n']%10==0 or r['n']==64:
  print('PASS n=%d C=%s all_types=%d'%(r['n'],val,count),flush=True)
print('EXACT k4 FRACTIONAL OPTIMALITY CERTIFIED: 57 DEGREES, %d TYPES'%N)
