import ErdosSimilarityGrowingGaps.Input
open Filter Topology
#check Nat.ceil_lt_add_one
#check Nat.le_ceil
#check Nat.floor_le
#check Nat.lt_floor_add_one
#check Nat.ceil_pos
#check Real.log_le_log
#check squeeze_zero
#check squeeze_zero'
#check tendsto_one_div_add_atTop_nhds_zero_nat
#check tendsto_one_div_atTop_nhds_zero_nat
#check tendsto_natCast_atTop_atTop
#check tendsto_one_div_atTop_nhds_zero_nat
#check Filter.Tendsto.div_atTop
#check Filter.Tendsto.const_div_atTop
#check Filter.Tendsto.atTop_div_const
#check Nat.one_le_ceil
#check Real.log_pos
