import ContinuumGeometric.RoutingTreeBounds
import Mathlib.Data.List.Chain
#check List.map_flatten
#check List.flatMap_def
#check List.sum_flatten
#check List.ofFn_const
#check List.map_ofFn
#check List.map_flatMap
#check List.pairwise_map
#check List.isChain_map
#check List.getLast?_cons
#check List.getLast?_eq_getLast
#check List.pairwise_append
#check List.nodup_flatMap
#check List.isChain_iff_getElem
#check List.getElem_mem
#check List.Pairwise.rel_get_of_lt
#check List.Pairwise.rel_getElem
#check List.getLast?_eq_some_iff
